0 0 dataAuditErrors
150 0 ILL_LAYER_PPLUS_DPL
203 0 ILL_LAYER_METCAP
234 0 ILL_ELEMENT_RPOLY2P
253 0 ILL_ELEMENT_RPOLYZ
357 0 DEVICE Error: Illegal nmosh device
390 0 ILL_LAYER_LVTDEF
407 0 NMOSW/NMOSMW for waffle trans we expect 1, 2, or 4 s/d conts, diffcont missing
409 0 NMOSW/NMOSMW for waffle trans we expect 1, 2, or 4 s/d conts, too much s/d cont
434 0 PMOSW/PMOSMW for waffle trans we expect 1, 2, or 4 s/d conts, diffcont missing
436 0 PMOSW/PMOSMW for waffle trans we expect 1, 2, or 4 s/d conts, too much s/d cont
608 0 INFO: Test or Probe pad < 60 * 60 U
645 0  INFO : standard pad met3 3 stack
647 0  INFO : standard pad met4 4 stack
652 0  INFO : POA pad met3 stack
654 0  INFO : POA pad met4 stack
827 0 Process Modules : PHDNWA850 not available for this process module
831 0 Process Modules : PHDNWB850 not available for this process module
833 0 Version od SBD5 obsolte or missing
841 0 Process Modules : SBD5 not available for this process module
1003 0 ILL_LAYER_PFIMP
1357 0 ERC Warning : Name of Spiral not identified
1358 0 ERC Warning : INDDEF does not define a correct spiral or is not valid for this process
1375 0 ERC Warning : illegal layer under spiral
1388 0 ERC Warning : Each INDDEF shape must be marked with a single INDDEF text label
1390 0 ERC Warning : multiple text on INDEF
1393 0 Error: METRES overlapping CONT or VIAx
1397 0 Error: MET1RES overlapping CONT or VIA1
1401 0 Error: MET2RES overlapping VIA1 or VIA2
1405 0 Error: MET3RES overlapping VIA2 or VIA3
1408 0 Error: MET4RES overlapping VIA3
1422 0 Error: MET1 resistors (shorts) must be rectangular
1424 0 Error: Number of MET1 resistor terminals != 2
1437 0 Error: MET2 resistors (shorts) must be rectangular
1439 0 Error: Number of MET2 resistor terminals != 2
1452 0 Error: MET3 resistors (shorts) must be rectangular
1454 0 Error: Number of MET3 resistor terminals != 2
1467 0 Error: MET4 resistors (shorts) must be rectangular
1469 0 Error: Number of MET4 resistor terminals != 2
1479 0 RVIA1 Definition layer: does not open all via conncetion, is shorted
1482 0 RVIA1 Definition layer: truncates via1, device shorted
1483 0 RVIA1 Definition layer: does not define a device
1487 0 RVIA1 Definition layer: over METRES
1494 0 RVIA2 Definition layer: does not open all via conncetion, is shorted
1497 0 RVIA2 Definition layer: truncates via2, device shorted
1498 0 RVIA2 Definition layer : does not define a device
1502 0 RVIA2 Definition layer: over METRES
1510 0 RVIA3 Definition layer: does not open all via conncetion, is shorted
1513 0 RVIA3 Definition layer: truncates via3, device shorted
1514 0 RVIA3 Definition layer : does not define a device
1518 0 RVIA3 Definition layer: over METRES
1519 0 rmet1 INFO : rmet1 does not open met1 for drc
1520 0 rmet2 INFO : rmet2 does not open met2 for drc
1521 0 rmet3 INFO : rmet3 does not open met3 for drc
1522 0 rvia1 INFO : rvia1 not opens met1/2 for drc
1523 0 rvia2 INFO : rvia2 not opens met2/3 for drc
1524 0 rmet4 INFO : rmet4 does not open met4 for drc
1525 0 rvia3 INFO : rvia3 not opens met3/4 for drc
1540 0 ERROR : POLY1 pin outside poly1
1541 0 ERROR : MET1 pin outside met1
1542 0 ERROR : MET2 pin outside met2
1543 0 ERROR: PADTSV pin outside METTSV
1545 0 ERROR : MET3 pin outside met3
1547 0 ERROR : MET4 pin outside met4
1548 0 ERROR : PAD pin outside pad metal
1557 0 BAD_SUBSTR_SUBTAP_FLOAT_ERC
1558 0 BAD_SUBSTR_SUBTAP_MULTCONN_ERC
1563 0 BAD_NWELL_WELLTAP_FLOAT_ERC
1564 0 BAD_NWELL_WELLTAP_MULTCONN_ERC
1568 0 INFO: any HVDEF used as isolation
1571 0 NMOSRF_OPEN_GATE
1577 0 PMOSRF_OPEN_GATE
1587 0 NMOSRF Element rule : fixed length = 0.35
1594 0 PMOSRF Element rule : fixed length = 0.35
1597 0 NMOSRF Element Rule : Gate width must be 5.0 U or 10 U
1600 0 PMOSRF Element Rule : Gate width must be 5.0 U or 10 U
1608 0 NMOSRF Element rule stripe width 5 U : max width = 200 U
1610 0 NMOSRF Element rule stripe width 10 U : max width = 200 U
1618 0 PMOSRF Element rule stripe width 5 U : max width = 150 U
1620 0 PMOSRF Element rule stripe width 10 U : max width = 150 U
1623 0 VERT10_P2 Element Rule : Base Ntub Perimeter/4 = 13.8
1627 0 VERT10_P3 Element Rule : Ptap Inside Perimeter/4 = 14.9
1636 0 VERT10_E1 Element Rule : NTUB enclosure of ntap = 0.45
1638 0 LAT2_P1 Element Rule : Emitter Perimeter/4 = 2
1641 0 LAT2_P2 Element Rule : Collector net_pdiff Perimeter/4 = 6.2
1644 0 LAT2_P3 Element Rule : Base Ntub Perimeter/4 = 10.0
1648 0 LAT2_P4 Element Rule : Ptap Inside Perimeter/4 = 11.1
1655 0 LAT2_W1 Element Rule : Lateral Base Width = 1
1664 0 LAT2_E1 Element Rule : NTUB enclosure of ntap = 0.45
1669 0 LAT2_G1 Element Rule : gate of lat2 transistor not connected to VDD or VCC
1671 0 NMOSH_O1/NMOSMH_O1 Element Rule : Gate Overlap of Ntub = 1.6 U
1681 0 NMOSH_S1/NMOSMH_S1 Element Rule : Gate Drain Diff spacing = 2.8
1690 0 NMOSH_E1/NMOSMH_E1 Element Rule : Poly Extension of gate = 0.6 U
1697 0 NMOSH_L1/NMOSMH_L1 Element Rule : Gate Length = 3.0 U
1699 0 NMOSH_X1/NMOSMH_X1 Element Rule : drain angles = 45, 8 vertices
1701 0 NMOSH_X1/NMOSMH_X1 Element Rule : edge length = 0.6 * sqrt(2)
1710 0 CVART_MIN_W Element Rule : cvart min w length = 10.0
1711 0 CVARM_MIN_W Element Rule : cvarm min w length = 10.0
1712 0 CVART_MIN_L Element Rule : cvart min l length = 2.0
1713 0 CVART_MIN_L Element Rule : cvart min l length = 2.0
1720 0 CVAR_W1 Element Rule : Gate unit width = 0.65
1723 0 CVAR_L1 Element Rule : Gate unit length = 6.60
1732 0 CVAR_X1 Element Rule : Gate spacing 1.0
1742 0 CVAR_Y1 Element Rule : Diff spacing 1.6
1743 0 Illegal device : Zener diode must have 0.2 implant ovlp
1744 0 ZD2SM24_O1 Element Rule : must have 0.2 U implant ovlp
1751 0 ZD2SM24_W1 Element Rule : must have 0.40 U n-implant edge length
1752 0 ZD2SM24_W1 Element Rule : must have 0.40 U p-implant edge length
1775 0 PHDNWA850/PHDNWB850 : Illegal layer on photo diode
1778 0 PHDNWA850/PHDNWB850 : Illegal layer on photo diode : met4,via3
1794 0 PHDNWA850/PHDNWB850 : ntub must not enclose any other data
1795 0 PHDNWA850/PHDNWB850 : ntub does not enclose OPTDEF
1796 0 PHDNWA850/PHDNWB850 : OPTDEF does not cover ntub and ndiff totally
1797 0 PHDNWA850/PHDNWB850 : OPTDEF layer outside of ntub and ndiff
1799 0 PHDNWA850/PHDNWB850 : text label for light terminal (P) missing on top level of hierarchie , please add label with terminal name on layer DEVDEF opto for correct extraction
1805 0 PHR001 PHDNWA850/PHDNWB850 : Illegal layer on photo diode OPTDEF  poly1/poly2/met1/met2/met3/met4
1806 0 PHR001 PHDNWA850/PHDNWB850 : Illegal layer on photo diode  OPTDEF : met4
1812 0 BRR001 PHDNWB850 : Illegal layer on photo diode PAD_BARC  poly1/poly2/met1/met2/met3/met4
1813 0 BRR001 PHDNWB850 : Illegal layer on photo diode PAD_BARC : met4
1816 0 PHDNWB850 PAD_BARC : PAD_BARC not rectangle, ATTENTION : data prep problem also, cannot be scaled by 1.5 percent by side if no rect
1818 0 W1BR PHDNWB850 : Minimum PAD_BARC width = 5
1825 0 ATTENTION : Layer SFCDEF should not be used on design data for DRC checking, SFCDEF is a special definition layer for MASK Fabrication
1831 0 INFO PHDNWB850 : single PAD_BARC shape in design,   max allowed width 150 U
1833 0 INFO PHDNWB850 : multiple PAD_BARC shape in design, max allowed width 50 U
1835 0 W2BR :  Maximum PAD_BARC width (1 PAD_BARC shape in design) = 150
1837 0 W3BR :  Maximum PAD_BARC width (multiple PAD_BARC shapes in design) = 50
1840 0 S1BRBR : Minimum PAD_BARC spacing = 7
1842 0 S1BRM1 : Minimum MET1 to PAD_BARC spacing = 1.1
1844 0 S1BRM2 : Minimum MET2 to PAD_BARC spacing = 1.4
1846 0 S1BRM3 : Minimum MET3 to PAD_BARC spacing = 1.6
1848 0 S1BRM4 : Minimum MET4 to PAD_BARC spacing = 2.3
1855 0 PHDNWA850/PHDNWB850 both on same design not allowed, different process option
1857 0 PHDNWA850 : PCOAT not allowed for this process
1858 0 PHDNWB850 : PCOAT not allowed for this process
1860 0 PHDNWA850_W1 : Minimum NTUB size (W and L) = 5
1861 0 PHDNWA850_W2 :  Maximum NTUB size (W and L) = 150
1865 0 PHDNWA850 W1/W2 : PHOTO diode is not square
2129 0 PHDNWA850_S1 : miss substrate ptap Fixed PDIFF to NTUB spacing = 0.4
2139 0 PHDNWA850_E1 : Fixed NTUB enclosure of NDIFF = 0.2
2146 0 PHDNWA850_S1 : Fixed PDIFF to NTUB spacing = 0.4
2149 0 PHDNWB850_W1 : Minimum PAD_BARC size (W and L) = 5
2150 0 PHDNWB850_W2 : Maximum PAD_BARC size (W and L) = 150
2154 0 PHDNWB850 W1/W2 : PHOTO diode is not square
2417 0 PHDNWB850_S1: miss substrate ptap Fixed PDIFF to NTUB spacing = 0.4
2427 0 PHDNWB850_E1 : Fixed NTUB enclosure of NDIFF = 0.2
2434 0 PHDNWB850_S1 : Fixed PDIFF to NTUB spacing = 0.4
2444 0 PHDNWB850_E2 : Fixed NDIFF enclosure of PAD_BARC = 0.5
2518 0 PHDNWB850_E2 : Fixed NDIFF enclosure of PAD_BARC = 0.5
2526 0 PHDNWB850_S2 : Fixed MET1 to PAD_BARC spacing = 1.2
2530 0 V1R003 : VIA1 overlapping SBDCON is not allowed
2532 0 S1COV1 : Minimum VIA1 spacing to SBDCON
2533 0 SBD5 DIODE : multiple SBDCON
2537 0 SDB5 DIODE : bad sbdcon
2544 0 SBD5_W DIODE fixed SBDCON width 0.4
2546 0 SBD5_W_L1 DIODE : SBDCON must have fixed L = 12 and fixed W = 0.4
2555 0 SBD5_X1 DIFF enclosure of SBDCON 0.3
2562 0 SBD5_X2 DIFF spacing 0.8
2569 0 SBD5_X3 DIFF spacing 0.55
2572 0 SBD5_X4 minimum NTUB ovlp ndiff 1.0
2576 0 SBD5_CATHODE_X5 SBD5_X5 minimum MET1 ovlp CONT 0.3
2580 0 SBD5_ANODE_X5 SBD5_X5 minimum MET1 ovlp CONT 0.3
2589 0 SBD5 DIODE : Illegal layer on Schottky diode
2607 0 SBD5 INFO : Orientation horizontal
2614 0 SBD5 INFO : Orientation vertical
2617 0 SBD5_R1 : Multiple SBD5 in a shared NTUB shape must have the same orientation
2620 0 PFR001 : DEVDEF_pfuse outside IPDEF is not allowed
2621 0 Error : RESDEF over DEVDEF_pfuse not allowed
2628 0 ERC Warning : This poly2 over HRES layer is high ohmic, but shorted for LVS
2629 0 CPMIM not supported over RFDEF
2635 0 CPMIM error : cpmim must be totally inside POLY2
2644 0 E1P2MC : Fixed poly2 enclosure of metcap 1.15
2646 0 CPMIM_R1 : CPMIM overlapping MET1 is not allowed
2659 0 CPMIM_R2 Element check: met3 metcap/poly1 plates of CPMIM not connected correctly
2660 0 CPMIM_R3 Element check: met2/poly2 plates of CPMIM not connected correctly
2662 0 W1PW : Minimum FIDEF width = 1.7
2665 0  S1PWPW : Minimum FIDEF spacing = 1
2668 0 S1NWPW : Minimum FIDEF to NTUB spacing = 6.5
2671 0 S1HVHV Minimum HVDEF spacing = 0.1
2673 0 HVR001 Each HVDEF shape must be marked with a single HVDEF text label
2675 0 INFO : multiple text on HVDEF
2676 0 INFO: NMOS18T HVDEF
2677 0 INFO: NMOS30M HVDEF
2680 0 HVR001 : Version of NMOS18T_REV1 obsolete
2681 0 HVR001 : Version of NMOS30M_REV2 obsolete
2682 0 HVR001 : No HVDEF on NMOS18T
2683 0 HVR001 : No HVDEF on NMOS30M
2684 0 HVR001 : Version of NMOS18T obsolete or missing
2685 0 HVR001 : Version of NMOS30M obsolete or missing
2686 0 HVR001 : HVDEF has illegal name on NMOS18T
2687 0 HVR001 : HVDEF has illegal name on NMOS30M
2712 0 NMOS18T/NMOS30M L Element Rule : Min gate length = 0.5 U
2713 0 NMOS18T/M W2 Element Rule : Min gate width/2 = 5 U
2726 0 NMOS30M X4 Element Rule : drain ndiff to source diff spacing (field plate) 2.0 U fixed
2733 0 NMOS18T X4 Element Rule : drain ndiff to source diff spacing (field plate) 1.8 U fixed
2742 0 NMOS30M X1 Element Rule : poly1 to drain diff spacing 0.4 U fixed
2749 0 NMOS18T X1 Element Rule : poly1 to drain diff spacing 0.35 U fixed
2759 0 NMOS30M/NMOS18T Element Rule X3 : ntub ovlp drain diff 1.85 U fixed
2768 0 NMOS30M Element Rule X5 : source diff ovlp of fidef = 1.5
2775 0 NMOS18T Element Rule X5 : source diff ovlp of fidef = 1.8
2782 0 NMOS30M/T Element Rule Y1 : poly1 to drain diff spacing 1 U fixed
2800 0 NMOS30M/T Element Rule Y2 : ntub stripe ovlp of drain diff = 3 
2806 0 NMOS18T/M Y3 Element Rule : poly width of gate connect = 2 U
2813 0 NMOS30M/T Element Rule Y4 : fidef ovlp of ntub = 2.8 U
2814 0 NMOS18T/M  Element Rule : nmos30m/nmos18t must have 1 ntub shape
2820 0 NMOS30M/T Element Rule Y5 : fidef to bulk pdiff spacing = 1.2 
2822 0 NMOS18T/M Y8 Element Rule : poly must be angled
2824 0 NMOS18T/M Y8 Element Rule : 45 degree poly must have length 0.7
2826 0 NMOS18T/M Y9 Element Rule : 45 degree poly must have length 0.7
2828 0 NMOS18T/M Y11 Element Rule : fidef must be angled
2830 0 NMOS18T/M Y11 Element Rule : fidef edge length = 0.75 * sqrt(2)
2834 0 NMOS18T/M Element Rule Y10 : fidef vertex to sdiff spacing = 1.75
2836 0 W2PW : Minimum PFIMP width = 0.8
2839 0  S2PWPW : Minimum PFIMP spacing = 1
2841 0 PWR002 : (PFIMP and not (HVDEF or SFCDEF)) is not allowed
2842 0 INFO : PMOSD30M HVDEF
2853 0 HVR001 : No HVDEF on PMOSD30M
2854 0 HVR001 : Version of PMOSD30M obsolete or missing
2855 0 HVR001 : Version of PMOSD30M is REV1 and obsolete, use rev2 
2856 0 HVR001 : HVDEF has illegal name on PMOSD30M
2875 0 PMOSD30M : Minimum CHANNEL length = 0.6
2876 0 PMOSD30M : Minimum CHANNEL width / N = 6.4
2889 0 PMOSD30M X1 Element Rule : POLY1 to DRAIN-PDIFF spacing = 0.3
2896 0 PMOSD30M Element Rule Y1 : POLY1 to DRAIN-PDIFF spacing = 0.3
2903 0 PMOSD30M X2 Element Rule : DRAIN-PDIFF to SOURCE-DIFF spacing (field plate) = 2.4
2910 0 PMOSD30M_X3 Element Rule : PFIMP overlap of SOURCE-DIFF = 0.6
2913 0 PMOSD30M_X4 Element Rule : Minimum NTUB enclosure of BULK-NDIFF = 0.8
2915 0 PMOSD30M_X5 Element Rule : NTUB to SUBSTRATE-PDIFF spacing = 2.4
3227 0 PMOSD30M_X5 Element Rule : miss substrate ptap Fixed PDIFF to NTUB spacing = 2.4
3243 0 PMOSD30M Element Rule X5  : bad layer between ntub and subtap
3252 0 PMOSD30M Element Rule X5 INFO : nofill should be drawn between ntub and subtap to avoid poly1 filling in intrinsic substrate
3260 0 PMOSD30M Element Rule X6 : NPLUS to PGATE spacing = 0.3
3269 0 PMOSD30M Element Rule Y2 : PFIMP enclosure of DRAIN-PDIFF = 2
3276 0 PMOSD30M Element Rule Y3 : BULK-NDIFF to DRAIN-PDIFF spacing = 4.25
3282 0 PMOSD30M Element Rule Y4 : POLY1 width of gate connection = 1.75
3284 0 PMOSD30M Element Rule Y5 : illegal vertices POLY1 45-deg corner (outside) = 0.55
3286 0 PMOSD30M Element Rule Y5 : POLY1 45-deg corner (outside) = 0.55
3290 0 PMOSD30M Element Rule Y5 : poly hole must not be angled 
3295 0 PMOSD30M Element Rule Y8 : Minimum PPLUS enclosure of PDIFFCON = 0.2
3309 0 PMOSD30M_R2 Element Rule R2 : SOURCE-PDIFF cannot be butted with BULK-NDIFF ring
3310 0 PMOSD30M_R2 Element Rule R2 : SOURCE-PDIFF cannot be butted with BULK-NDIFF ring
3316 0 PMOSD30M Element Rule Y7 : Minimum PDIFF enclosure of PDIFFCON = 0.2
3318 0 PMOSD30M Element Rule Y7: fixed size of butting ndiff square 0.9 x 0.9
3321 0 PMOSD30M INFO : min spacing of butting ndiff to ndiff 1.6 U
3340 0 PMOSD30M_R1: Bulk and source must be connected with met1 (check1)
3356 0 PMOSD30M_R1: Bulk and source must be connected with met1 (check2)
3375 0 PMOSD30M_R1: Bulk and source must be connected with met1 also for single device
3386 0 PMOSD30M_HVR003_sources_must_be_connected_together
3392 0 PMOSD30M Element Rule : pfimp must be rectangle
3393 0  PMOSD30M : this device not supported for any pad over active application
3394 0 INFO : PMOS30M HVDEF
3405 0 HVR001 : No HVDEF on PMOS30M
3406 0 HVR001 : Version of PMOS30M obsolete or missing
3407 0 HVR001 : HVDEF has illegal name on PMOS30M
3426 0 PMOS30M : Minimum CHANNEL length = 0.6
3427 0 PMOS30M : Minimum CHANNEL width / 2 = 6.4
3440 0 PMOS30M X1 Element Rule : POLY1 to DRAIN-PDIFF spacing = 0.3
3447 0 PMOS30M Element Rule Y1 : POLY1 to DRAIN-PDIFF spacing = 0.3
3454 0 PMOS30M X2 Element Rule : DRAIN-PDIFF to SOURCE-DIFF spacing (field plate) = 2.4
3461 0 PMOS30M_X3 Element Rule : PFIMP overlap of SOURCE-DIFF = 0.6
3464 0 PMOS30M_X4 Element Rule : Minimum NTUB enclosure of BULK-NDIFF = 0.8
3466 0 PMOS30M_X5 Element Rule : NTUB to SUBSTRATE-PDIFF spacing = 2.4
3778 0 PMOS30M_X5 Element Rule : miss substrate ptap Fixed PDIFF to NTUB spacing = 2.4
3794 0 PMOS30M Element Rule X5  : bad layer between ntub and subtap
3802 0 PMOS30M Element Rule X5 INFO : nofill should be drawn between ntub and subtap to avoid poly1 filling in intrinsic substrate
3811 0 PMOS30M Element Rule Y2 : PFIMP enclosure of DRAIN-PDIFF = 2
3818 0 PMOS30M Element Rule Y3 : BULK-NDIFF to DRAIN-PDIFF spacing = 4.25
3824 0 PMOS30M Element Rule Y4 : POLY1 width of gate connection = 1.75
3826 0 PMOS30M Element Rule Y5 : illegal vertices POLY1 45-deg corner (outside) = 0.55
3828 0 PMOS30M Element Rule Y5 : POLY1 45-deg corner (outside) = 0.55
3832 0 PMOS30M Element Rule Y5 : poly hole must not be angled 
3843 0 PMOS30M_HVR003_sources_must_be_connected_together
3849 0 PMOS30M Element Rule : pfimp must be rectangle
3850 0  PMOS30M : this device not supported for any pad over active application
3852 0 INFO: ESDPD12 HVDEF
3854 0 HVR001 : Version of ESDPD12 obsolete or missing
3855 0 HVR001 : HVDEF has illegal name on ESDPD12
3857 0 INFO: ESDPD26 HVDEF
3859 0 HVR001 : Version of ESDPD26 obsolete or missing
3860 0 HVR001 : HVDEF has illegal name on ESDPD26
3862 0 INFO: ESDPD18 HVDEF
3864 0 HVR001 : Version of ESDPD18 obsolete or missing
3865 0 HVR001 : HVDEF has illegal name on ESDPD18
3867 0 INFO: ESDPD30 HVDEF
3869 0 HVR001 : Version of ESDPD30 obsolete or missing
3870 0 HVR001 : HVDEF has illegal name on ESDPD30
3872 0 INFO: ESDGCN5 HVDEF
3874 0 HVR001 : Version of ESDGCN5 obsolete or missing
3875 0 HVR001 : HVDEF has illegal name on ESDGCN5
3877 0 INFO: ESDGCP5 HVDEF
3879 0 HVR001 : Version of ESDGCP5 obsolete or missing
3880 0 HVR001 : HVDEF has illegal name on ESDGCP5
3882 0 INFO: ESDFDP5 HVDEF
3884 0 HVR001 : Version of ESDFDP5 obsolete or missing
3885 0 HVR001 : HVDEF has illegal name on ESDFDP5
3887 0 INFO: ESDFDN5 HVDEF
3889 0 HVR001 : Version of ESDFDN5 obsolete or missing
3890 0 HVR001 : HVDEF has illegal name on ESDFDN5
3892 0 HVR001 : HVDEF does not enclose a valid HV-device, bad HVDEF or bad device
3911 0 ESDPD12_L Element Rule : CATHODE-NTUB length = 1.3
3912 0 ESDPD12_W1 Element Rule : Minimum CATHODE-NTUB width = 10
3913 0 ESDPD12_W2 Element Rule : Maximum CATHODE-NTUB width = 10000
3922 0 ESDPD12_X2 Element Rule : NTUB enclosure of NDIFF = 0.3
3931 0 ESDPD12_Y2 Element Rule : NTUB enclosure of NDIFF = 1.5
3938 0 ESDPD12_X3 Element Rule : PDIFF to NTUB spacing = 0.5
3945 0 ESDPD12_Y3 Element Rule : PDIFF to NTUB spacing = 2
3952 0 ESDPD12_X4 Element Rule : PDIFF width = 0.7
3967 0 ESDPD18_L Element Rule : CATHODE-NTUB length = 1.7
3968 0 ESDPD18_W1 Element Rule : Minimum CATHODE-NTUB width = 10
3969 0 ESDPD18_W2 Element Rule : Maximum CATHODE-NTUB width = 10000
3978 0 ESDPD18_X2 Element Rule : NTUB enclosure of NDIFF = 0.5
3987 0 ESDPD18_Y2 Element Rule : NTUB enclosure of NDIFF = 1.5
3994 0 ESDPD18_X3 Element Rule : PDIFF to NTUB spacing = 0.5
4001 0 ESDPD18_Y3 Element Rule : PDIFF to NTUB spacing = 2
4008 0 ESDPD18_X4 Element Rule : PDIFF width = 0.7
4011 0 ESDPD18_X5 Element Rule : Minimum CATHODE-MET1 width = 1.6
4028 0 ESDPD26_L Element Rule : CATHODE-NTUB length = 2.1
4029 0 ESDPD26_W1 Element Rule : Minimum CATHODE-NTUB width = 10
4030 0 ESDPD26_W2 Element Rule : Maximum CATHODE-NTUB width = 10000
4039 0 ESDPD26_X2 Element Rule : NTUB enclosure of NDIFF = 0.7
4048 0 ESDPD26_Y2 Element Rule : NTUB enclosure of NDIFF = 1.7
4055 0 ESDPD26_X3 Element Rule : PDIFF to NTUB spacing = 1
4062 0 ESDPD26_Y3 Element Rule : PDIFF to NTUB spacing = 2
4069 0 ESDPD26_X4 Element Rule : PDIFF width = 0.7
4072 0 ESDPD26_X5 Element Rule : Minimum CATHODE-MET1 width = 1.9
4089 0 ESDPD30_L Element Rule : CATHODE-NTUB length = 2.3
4090 0 ESDPD30_W1 Element Rule : Minimum CATHODE-NTUB width = 10
4091 0 ESDPD30_W2 Element Rule : Maximum CATHODE-NTUB width = 10000
4100 0 ESDPD30_X2 Element Rule : NTUB enclosure of NDIFF = 0.8
4109 0 ESDPD30_Y2 Element Rule : NTUB enclosure of NDIFF = 1.8
4116 0 ESDPD30_X3 Element Rule : PDIFF to NTUB spacing = 1.5
4123 0 ESDPD30_Y3 Element Rule : PDIFF to NTUB spacing = 2
4130 0 ESDPD30_X4 Element Rule : PDIFF width = 0.7
4133 0 ESDPD30_X5 Element Rule : Minimum CATHODE-MET1 width = 1.9
4148 0 ESDFDP5_L Element Rule : ANODE-PDIFF length = 0.7
4149 0 ESDFDP5_W1 Element Rule : Minimum ANODE-PDIFF width = 10
4150 0 ESDFDP5_W2 Element Rule : Maximum ANODE-PDIFF width = 200
4157 0 ESDFDP5_X2 Element Rule : PDIFF to NDIFF spacing = 0.7
4164 0 ESDFDP5_X3 Element Rule : NDIFF width = 0.7
4177 0 ESDFDN5_L Element Rule : CATHODE-NDIFF length = 0.7
4178 0 ESDFDN5_W1 Element Rule : Minimum CATHODE-NDIFF width = 10
4179 0 ESDFDN5_W2 Element Rule : Maximum CATHODE-NDIFF width = 200
4186 0 ESDFDN5_X2 Element Rule : NDIFF to PDIFF spacing = 0.7
4193 0 ESDFDN5_X3 Element Rule : PDIFF width = 0.7
4219 0 ESDGCN5_L Element Rule : CATHODE-NDIFF length = 0.7
4220 0 ESDGCN5_W1 Element Rule : Minimum CATHODE-NDIFF width = 0.7
4221 0 ESDGCN5_W2 Element Rule : Maximum CATHODE-NDIFF width = 100
4228 0 ESDGCN5_X2 Element Rule : NDIFF to PDIFF spacing = 0.7
4235 0 ESDGCN5_X3 Element Rule : PDIFF width = 0.7
4263 0 ESDGCP5_L Element Rule : ANODE-PDIFF length = 0.7
4264 0 ESDGCP5_W1 Element Rule : Minimum ANODE-PDIFF width = 0.7
4265 0 ESDGCP5_W2 Element Rule : Maximum ANODE-PDIFF width = 100
4272 0 ESDGCP5_X2 Element Rule : PDIFF to NDIFF spacing = 0.7
4279 0 ESDGCP5_X3 Element Rule : NDIFF width = 0.7
4287 0 MOSW : Waffle trans : cannot mix different size of holes over same diff
4289 0 MOSW : Waffle trans hole : poly hole size incorrect
4295 0 MOSW : Waffle trans gate : these gates cannot be identified correctly due to size of poly hole and are discarded from LVS
4303 0 NMOSW : Waffle trans : shorted device nmosw
4311 0 NMOSMW : Waffle trans : shorted device nmosmw
4319 0 PMOSW : Waffle trans : shorted device pmosw
4327 0 PMOSMW : Waffle trans : shorted device pmosmw
4347 0 NMOSW : Waffle trans : s/d of waffle trans not connected to other sd over same waffle diff, Inactive Unit found, causes encreasing current flow in neighbouring devices
4367 0 NMOSMW : Waffle trans : s/d of waffle trans not connected to other sd over same waffle diff, Inactive Unit found, causes encreasing current flow in neighbouring devices
4387 0 PMOSW : Waffle trans : s/d of waffle trans not connected to other sd over same waffle diff, Inactive Unit found, causes encreasing current flow in neighbouring devices
4407 0 PMOSMW : Waffle trans : s/d of waffle trans not connected to other sd over same waffle diff, Inactive Unit found, causes encreasing current flow in neighbouring devices
4410 0  NMOSW for waffle trans we expect 1, 2, or 4 s/d conts
4413 0  NMOSMW for waffle trans we expect 1, 2, or 4 s/d conts
4424 0 NMOSW_W : Waffle trans : fixed channel length 4 = 2.8 sqrt(2)
4425 0 NMOSW_L1 : Waffle trans : min channel length 0.5 = 0.35 sqrt(2)
4426 0 NMOSW_L2 : Waffle trans : max channel length 3.0 = 2.1 sqrt(2)
4427 0 NMOSMW_W : Waffle trans : fixed channel length 4 = 2.8 sqrt(2)
4428 0 NMOSMW_L1 : Waffle trans : min channel length 0.5 = 0.35 sqrt(2)
4429 0 NMOSMW_L2 : Waffle trans : max channel length 3.0 = 2.1 sqrt(2)
4449 0 NMOSW_S1 : Waffle trans : fixed diffcon to gate spacing 1.2 0.85 * sqrt(2)
4469 0 NMOSMW_S1 : Waffle trans : fixed diffcon to gate spacing 1.2 0.85 * sqrt(2)
4472 0  PMOSW for waffle trans we expect 1, 2, or 4 s/d conts
4475 0  PMOSMW for waffle trans we expect 1, 2, or 4 s/d conts
4486 0 PMOSW_W : Waffle trans : fixed channel length 4 = 2.8 sqrt(2)
4487 0 PMOSW_L1 : Waffle trans : min channel length 0.5 = 0.35 sqrt(2)
4488 0 PMOSW_L2 : Waffle trans : max channel length 3.0 = 2.1 sqrt(2)
4489 0 PMOSMW_W : Waffle trans : fixed channel length 4 = 2.8 sqrt(2)
4490 0 PMOSMW_L1 : Waffle trans : min channel length 0.5 = 0.35 sqrt(2)
4491 0 PMOSMW_L2 : Waffle trans : max channel length 3.0 = 2.1 sqrt(2)
4511 0 PMOSW_S1 : Waffle trans : fixed diffcon to gate spacing 1.2 0.85 * sqrt(2)
4531 0 PMOSMW_S1 : Waffle trans : fixed diffcon to gate spacing 1.2 0.85 * sqrt(2)
4532 0 ILL_LAYER_LVTA
4533 0 ILL_LAYER_LVPTUB
4536 0 ILL_ELEMENT_RPOLYH_RPOLYZ
4539 0 ILL_ELEMENT_RPOLY2P_RPOLY2PH
4540 0 NTUB net layer must not be used in layout view
4541 0 POLY1 net layer must not be used in layout view
4542 0 POLY2 net layer must not be used in layout view
4543 0 CONT net layer must not be used in layout view
4544 0 MET1 net layer must not be used in layout view
4545 0 VIA1 net layer must not be used in layout view
4546 0 MET2 net layer must not be used in layout view
4547 0 VIA2 net layer must not be used in layout view
4548 0 MET3 net layer must not be used in layout view
4549 0 VIA3 net layer must not be used in layout view
4550 0 MET4 net layer must not be used in layout view
4552 0 Warning: No MET4 on MET4 Pin
4554 0 Warning: No POLY1 on POLY1 Pin
4556 0 Warning: No MET1 on MET1 Pin
4558 0 Warning: No MET2 on MET2 Pin
4560 0 Warning: No MET3 on MET3 Pin
4569 0 REC002 REC002 NTUB not multiple 45 degrees REC002
4570 0 REC002 REC002 DIFF not multiple 45 degrees REC002
4571 0 REC002 REC002 MIDOX not multiple 45 degrees REC002
4572 0 REC002 REC002 POLY1 not multiple 45 degrees REC002
4573 0 REC002 REC002 NPLUS not multiple 45 degrees REC002
4574 0 REC002 REC002 PPLUS not multiple 45 degrees REC002
4575 0 REC002 REC002 HRES not multiple 45 degrees REC002
4576 0 REC002 REC002 CONT not multiple 45 degrees REC002
4577 0 REC002 REC002 MET1 not multiple 45 degrees REC002
4578 0 REC002 REC002 VIA1 not multiple 45 degrees REC002
4579 0 REC002 REC002 MET2 not multiple 45 degrees REC002
4580 0 REC002 REC002 VIA2 not multiple 45 degrees REC002
4581 0 REC002 REC002 MET3 not multiple 45 degrees REC002
4582 0 REC002 REC002 VIA3 not multiple 45 degrees REC002
4583 0 REC002 REC002 MET4 not multiple 45 degrees REC002
4584 0 REC002 REC002 PAD not multiple 45 degrees REC002
4595 0 INFO: hot nwell
4598 0 NW_W_1 Minimum NTUB width = 1.7
4600 0 NW_W_2 Minimum HOT_NTUB width = 3
4614 0 NW_S_1 Minimum spacing of NTUB with different potential = 3
4617 0 NW_S_2 Minimum spacing of NTUB with same potential = 1
4619 0 NW_S_2 Minimum spacing of NTUB with same potential = 1 notch
4632 0 OD_W_1 Minimum DIFF width to define the width of NMOS/PMOS = 0.4 ngate
4641 0 OD_W_1 Minimum DIFF width to define the width of NMOS/PMOS = 0.4 pgate
4643 0 OD_W_2 Minimum DIFF width for interconnection (NDIFF or PDIFF) = 0.3
4646 0 OD_S_1 Minimum DIFF spacing = 0.6
4648 0 OD_S_1 Minimum DIFF spacing = 0.6 notch 
4654 0 OD_C_1 Minimum NTUB enclosure of NDIFF = 0.2
4658 0 OD_C_2 Minimum NDIFF to NTUB spacing = 1.2
4673 0 OD_C_3 Minimum NDIFF to HOT_NTUB spacing (no PTAP in between) = 2.6
4677 0 OD_C_4 Minimum NTUB enclosure of PDIFF = 1.2
4679 0 OD_C_5 Minimum PDIFF to NTUB spacing = 0.2
4682 0 OD_C_6a Minimum PDIFF to NGATE spacing = 0.45
4687 0 OD_C_6b Minimum NDIFF to PGATE spacing = 0.45
4695 0 OD_S_2B Minimum NDIFF to non-butting PDIFF spacing = 0.6
4696 0 INFO : nplus pplus overlap
4699 0 INFO: DIFF missing nplus/pplus
4701 0 W1XM Minimum MIDOX width = 0.6
4709 0 OD2_E_1 Minimum MIDOX enclosure of DIFF = 0.6
4712 0 OD2_S_1 Minimum MIDOX spacing = 0.6
4714 0 OD2_C_1 Minimum MIDOX to DIFF spacing = 0.6
4716 0 BAD1XM MIDOX outside GATE is not allowed
4728 0 PO_W_1a Minimum GATE length of PMOS = 0.35
4730 0 PO_W_1b Minimum GATE length of PMOSM = 0.5
4732 0 PO_W_2a Minimum GATE length of NMOS = 0.35
4734 0 PO_W_2b Minimum GATE length of NMOSM = 0.5
4737 0 PO_W_3 Minimum POLY1 width for interconnect = 0.35
4740 0 PO_S_1 Minimum POLY1 spacing = 0.45 
4742 0 PO_S_1 Minimum POLY1 spacing = 0.45 notch
4744 0 PO_C_1 Minimum POLY1 to DIFF spacing = 0.2
4753 0 PO_C_2 Minimum DIFF extension of GATE = 0.5
4756 0 PO_O_1 Minimum POLY1 extension of GATE = 0.4
4758 0 PO_R_1 Minimum density of POLY1 area [%] = 14
4760 0 PO2_W_1 Minimum CPOLY width = 0.8
4763 0 PO2_S_1 Minimum CPOLY spacing = 0.65
4766 0 PO2_E_1 Minimum POLY1 enclosure of CPOLY = 1
4769 0 PO2_E_2 Minimum CPOLY enclosure of POLY2CON = 0.6
4771 0 PO2_C_1 Minimum POLY1CON to CPOLY spacing = 1.2
4773 0 PO2_W_2 Minimum POLY2 width = 0.65
4776 0 PO2_S_2 Minimum POLY2 spacing = 0.5
4778 0 PO2_S_2 Minimum POLY2 spacing = 0.5 notch
4780 0 PO2_S_2 Minimum POLY2 spacing = 0.5 notch
4782 0 PO2_S_2 Minimum POLY2 spacing = 0.5 notch
4784 0 PO2_W_3 Minimum RPOLYH width = 0.8
4787 0 PO2_S_3 Minimum RPOLYH spacing = 0.75
4789 0 PO2_S_3 Minimum RPOLYH spacing = 0.75 notch
4791 0 PO2_C_2 Minimum DIFF to POLY2 spacing = 0.2
4793 0 PO2_C_3 Minimum POLY1 to POLY2 spacing = 0.65
4798 0 PO2_E_3 Minimum POLY2 enclosure of POLY2CON = 0.25
4799 0 PO2_R_1 POLY2 on DIFF is not allowed
4801 0 PP_W_1 Minimum PPLUS width = 0.6
4804 0 PP_S_1 Minimum PPLUS spacing = 0.6
4806 0 PP_C_1 Minimum PPLUS to DIFF spacing = 0.35
4808 0 PP_C_2 Minimum PPLUS to NGATE spacing = 0.45
4814 0 PP_C_3 Minimum PPLUS extension of PGATE = 0.45
4816 0 PP_O_1  Minimum overlap of PPLUS and DIFF = 0.45
4819 0 PP_E_1 Minimum PPLUS extension of DIFF = 0.25
4826 0 PP_C_5 NP_C_5 NPC5/PPC5  Minimum PPLUS to NPLUS spacing on POLY1 = 0.25
4828 0 PP_C_6 Minimum PPLUS to NPLUS spacing on DIFF with same potential = 0
4830 0 NP_W_1 Minimum NPLUS width = 0.6
4833 0 NP_S_1 Minimum NPLUS spacing = 0.6
4835 0 NP_C_1 Minimum NPLUS to DIFF spacing = 0.35
4839 0 NP_C_2 Minimum NPLUS to PGATE spacing = 0.45
4842 0 NP_C_3 Minimum NPLUS extension of NGATE = 0.45
4844 0 NP_O_1  Minimum overlap of NPLUS and DIFF = 0.45
4847 0 NP_E_1 Minimum NPLUS extension of DIFF = 0.25
4849 0 NP_C_6 Minimum NPLUS to PPLUS spacing on DIFF with same potential = 0
4857 0 CO_W_1 Fixed CONT width = 0.4
4860 0 CO_S_1 Minimum CONT spacing = 0.4
4862 0 CO_C_1 Minimum DIFFCON to GATE spacing = 0.3
4864 0 CO_C_2  Minimum POLY1CON to DIFF spacing = 0.4
4867 0 CO_E_1 Minimum DIFF enclosure of DIFFCON = 0.15
4870 0 CO_E_2 Minimum POLY1 enclosure of POLY1CON = 0.2
4875 0 CO_E_3 Minimum PPLUS enclosure of PDIFFCON = 0.25
4878 0 CO_E_4  Minimum NPLUS enclosure of NDIFFCON = 0.25
4879 0 CO_R_1 POLY1CON on DIFF is not allowed
4882 0 CO_R_2 Butted CONT is not allowed
4883 0 R0_1_CT CONT without DIFF or POLY1 or POLY2 is not allowed
4884 0 ERC Warning: CONT without metal1
4885 0 ERC Warning: CONT without diff or poly
4887 0 M1_W_1 Minimum MET1 width = 0.5
4890 0 M1_S_1  Minimum MET1 spacing = 0.45
4933 0 M1_S_2 Minimum MET1 to WIDE_MET1 spacing = 0.8 wide wide
4935 0 M1_S_2 Minimum MET1 to WIDE_MET1 spacing = 0.8 wide small
4940 0 M1_E_1 Minimum MET1 enclosure of CONT = 0.15
4942 0 M1_R_1 Minimum density of MET1 area [%] = 30
4944 0 VIA1_W_1 Fixed VIA1 width = 0.5
4947 0 VIA1_S_1 Minimum VIA1 spacing = 0.45
4952 0 VIA1_E_1 Minimum MET1 enclosure of VIA1 = 0.2
4953 0 R01V1 VIA1 without MET1 is not allowed
4954 0 ERC Warning: Via1 missing metal1
4956 0 M2_W_1 Minimum MET2 width = 0.6
4959 0 M2_S_1 Minimum MET2 spacing = 0.5
5002 0 M2_S_2 Minimum MET2 to WIDE_MET2 spacing = 0.8 wide wide
5004 0 M2_S_2 Minimum MET2 to WIDE_MET2 spacing = 0.8 wide small
5009 0 M2_E_1 Minimum MET2 enclosure of VIA1 = 0.15
5011 0 M2_R_1 Minimum density of MET2 area [%] = 30
5013 0 VIA2_W_1 Fixed VIA2 width = 0.5
5016 0 VIA2_S_1 Minimum VIA2 spacing = 0.45
5021 0 VIA2_E_1 Minimum MET2 enclosure of VIA2 = 0.2
5022 0 R01V2 VIA2 without MET2 is not allowed
5023 0 ERC Warning: Via2 missing metal2
5025 0 M3_W_1  Minimum MET3 width = 0.6
5028 0 M3_S_1 Minimum MET3 spacing = 0.5
5033 0 M3_E_1 Minimum MET3 enclosure of VIA2 = 0.15
5076 0 M3S2 Minimum MET3 to WIDE_MET3 spacing = 0.8 wide wide 
5078 0 M3_S_2 Minimum MET3 to WIDE_MET3 spacing = 0.8 wide small
5080 0 M3_R_1 Minimum density of MET3 area [%] = 30
5082 0 VIA3_W_1 Fixed VIA3 width = 0.5
5085 0 VIA3_S_1 Minimum VIA3 spacing = 0.45
5090 0 VIA3_E_1 Minimum MET3 enclosure of VIA3 = 0.2
5091 0 R01V3 VIA3 without MET3 is not allowed
5092 0 ERC Warning: VIA3 missing met3
5094 0 M4_W_1 Minimum MET4 width = 0.6
5097 0 M4_S_1 Minimum MET4 spacing = 0.6
5102 0 M4_E_1 Minimum MET4 enclosure of VIA3 = 0.15
5145 0 M4_S_2 Minimum MET4 to WIDE_MET4 spacing = 0.8 wide wide
5147 0 M4_S_2 Minimum MET4 to WIDE_MET4 spacing = 0.8 wide small
5148 0 ERC Warning: VIA3 missing met4
5150 0 M4_R_1 Minimum density of MET4 area [%] = 30
5155 0 INFO: illegal diffusion on pad
5157 0 INFO: illegal poly1 on pad
5159 0 INFO: illegal poly2 on pad
5161 0 INFO: illegal contact on pad
5163 0 CBR1 CB_R_1 missing met1
5165 0 CBR1 CB_R_1 missing met2
5167 0 CBR1 CB_R_1 missing met3
5170 0 CBR1 CB_R_1 missing met4
5171 0 ERC Warning: Missing top met4 on Test or Probe pad
5173 0 W1PA Minimum PAD width = 15
5175 0 CB_W_1 Minimum bonding PAD width (85um preferred, 60um on request) = 70
5177 0 CB_W_1_G1 Minimum bonding PAD width (85um preferred, 60um on request) = 70 preferred 85
5180 0 CB_S_1 Minimum PAD spacing = 15
5184 0 CB_E_1 Minimum MET1 enclosure of PAD_ST = 5
5188 0 CB_E_2 Minimum MET2 enclosure of PAD_3OA = 5
5191 0 CB_E_3 Minimum MET3 enclosure of PAD = 5
5194 0 CB_E_4 Minimum MET4 enclosure of PAD = 5
5213 0 CB_E_5 Minimum MET1 enclosure of the nearest PADVIA1 = 3
5256 0 CB_E_5 bad diamond shape of pad via array must have 4 corners
5259 0 CB_E_5 bad diamond shape of pad via array
5260 0 CB_E_7 bad diamond shape of padvia2 array must have 4 corners
5263 0 CB_E_7 bad diamond shape of padvia2 array
5274 0 CB_E_9 bad diamond shape of padvia3 array must have 4 corners
5277 0 CB_E_9 bad diamond shape of padvia3 array
5280 0 CB_E_7 Minimum MET2 enclosure of the nearest PADVIA2 and PADVIA1 = 3 padvia1
5283 0 CB_E_7 Minimum MET2 enclosure of the nearest PADVIA2 and PADVIA1 = 3 padvia2
5286 0 CB_E_9  Minimum MET3 enclosure of the nearest PADVIA3 and PADVIA2 = 3
5289 0 CB_E_9 Minimum MET3 enclosure of the nearest PADVIA3 and PADVIA2 = 3
5292 0 CB_E_11 Minimum MET4 enclosure of the nearest PADVIA3 = 3
5295 0 CB_S_2 Minimum PADVIA1 spacing = 0.8
5298 0 CB_S_3 Minimum PADVIA2 spacing = 0.8
5301 0 CB_S_4 Minimum PADVIA3 spacing = 0.8
5303 0 CB_C_1 Minimum PADVIA2 to PADVIA1 spacing = 0.3
5305 0 CB_C_2 Minimum PADVIA3 to PADVIA2 spacing = 0.3
5307 0 CB_R_2 Minimum ratio of PADVIA1 area to PAD_ST area [%] = 5
5309 0 CB_R_3 Minimum ratio of PADVIA2 area to PAD_ST area [%] = 5
5311 0 CB_R_4 Minimum ratio of PADVIA3 area to PAD_ST area [%] = 5
5312 0 CB_C_1 Illegal pad via stack via1/via2
5313 0 CB_C_2 Illegal pad via stack via2/via3
5318 0 S1DFPA Minimum PAD_ST to DIFF spacing = 9
5320 0 S1P1PA Minimum PAD_ST to POLY1 spacing = 9
5322 0 S1P2PA Minimum PAD_ST to POLY2 spacing = 9
5325 0 S1M1PA Minimum PAD_ST to MET1 spacing (different net) = 9
5328 0 S1M2PA Minimum PAD_ST to MET2 spacing (different net) = 9
5331 0 S1M3PA Minimum PAD_ST to MET3 spacing (different net) = 9
5334 0 S1M4PA Minimum PAD_ST to MET4 spacing (different net) = 9
5335 0 R01PA PAD without MET4 is not allowed
5336 0 TOPOLOGY PROBLEM : POA pad met 4 stack found, but totally enclosed by MET1
5339 0 Illegal POA pad met3 stack for 4 metal process
5341 0 TOPOLOGY PROBLEM : POA pad met 4 stack found, but totally enclosed by MET2
5343 0 CB_W_1_G1 Minimum bonding PAD width (85um preferred, 60um on request) = 70 Min bonding pad width 70 U, 85 U preferred, 60 U request
5345 0 CB_W_1_G1 Minimum bonding PAD width (85um preferred, 60um on request) = 70 Min bonding pad width 70 U, 85 U preferred, 60 U request
5347 0 CB_W_1_G1 Minimum bonding PAD width (85um preferred, 60um on request) = 70 Min bonding pad width 70 U, 85 U preferred, 60 U request
5348 0 PAR006 : PAD_4OA overlapping VIA2 is not allowed
5351 0 S2PAV2 : Minimum PAD_4OA to VIA2 spacing = 0.5
5354 0 S1PAV3 : Minimum PAD_4OA to VIA3 spacing = 0.25
5358 0 E1PAV3 Minimum PAD_4OA enclosure of VIA3 = 0.2
5366 0 PAR007 : (PAD_4OA sized by -0.7) overlapping VIA3 is not allowed
5368 0 PAR002 KEPOUT definition : (PAD_4OA AND KEPOUT) is not allowed
5371 0 S2KOPA KEPOUT definition : Minimum spacing PAD_4OA to (KEPOUT or SFCDEF) = 7
5377 0 S2M3PA Minimum PAD_4OA to MET3 spacing (different net) = 7
5380 0 S2M4PA Minimum PAD_4OA to MET4 spacing (different net) = 7
5381 0 PAR010 : PAD_OA overlapping CPOLY is not allowed
5432 0 PAR008 Density : Line-of-sight looking through all VIA3 rows at any angle must be blocked by at least one VIA3,via3 density probably too small for this rule
5461 0 PAR008 Density : use 1 row of via3 at min ovlp of PAD poa
5479 0 PAR008 : Line-of-sight looking through all VIA3 rows at any angle must be blocked by at least one VIA3
5525 0 PAR009 :  LV_GATE L > 0.5 PAD_OA overlapping GATE is not allowed,  No valid exemption for LV_GATE, L > 0.5
5531 0 PAR009 : LV_GATE L=LMIN W < 400  PAD_OA overlapping GATE is not allowed, No valid exemption for LV_GATE, L <= 0.5, but total W < 400 U
5564 0  PAR009 : NMOS30M/NMOS18T  L > LMIN  PAD_OA overlapping GATE is not allowed,  No valid exemption for HV_GATE, L > 0.5 LMIN
5579 0 PAR009 : NMOS30M/NMOS18T  L=LMIN W < 400 PAD_OA overlapping GATE is not allowed, No valid exemption for HV_GATE, L <= 0.5 LMIN, but total W < 400 U
5607 0 PAR009 : NMOSH  L > LMIN  PAD_OA overlapping NMOSH_GATE is not allowed,  No valid exemption for NMOSH GATE, L > 3.0
5613 0 PAR009 : NMOSH  L = LMIN < 400 PAD_OA overlapping NMOSH_GATE is not allowed, No valid exemption for NMOSH__GATE, L <= 3.0, but total W < 400 U
5631 0 PAR009: PAD_4OA overlapping GATE is not allowed,  Exemptions : HV_GATE  with HVDEF text ESD*/ LV_GATE L <= 0.5, total active trans W >= 400/ HV_GATE L = MIN, total active trans W >= 400 / LV_GATE overlapping holed POLY1 ..waffel trans
5633 0 W1HR Minimum HRES width = 0.6
5636 0 S1HRHR Minimum HRES spacing = 0.6
5637 0 BAD1HR HRES is not allowed over DIFF
5638 0 BAD2HR HRES is not allowed over NPLUS
5639 0 BAD3HR HRES is not allowed over POLY1
5643 0 E1HRP2 Minimum HRES enclosure of POLY2 = 3
5645 0 S1HRP1 Minimum HRES to POLY1 spacing = 0.35
5647 0 S1HRP2 Minimum HRES to POLY2 spacing = 3
5649 0 S1DFHR  Minimum HRES to DIFF spacing = 0.35
5651 0 W1LV Minimum LVTDEF width = 0.6
5654 0 S1LVLV Minimum LVTDEF spacing = 0.6
5661 0 E1LVAA Minimum LVTDEF enclosure of DIFF = 0.25
5663 0 S1AALV Minimum LVTDEF to DIFF spacing = 0.35
5664 0 LVR001 LVTDEF over ZENER is not allowed
5666 0 LVR002 LVTDEF outside GATE is not allowed
5667 0 LVR003: LVTA outside SFCDEF will be removed and regenerated
5668 0 LFR001: LVPTUB outside SFCDEF will be removed and regenerated
5674 0 NMOSML_R1 Minimum GATE length of NMOSML = 0.5
5680 0 PMOSML_R1 Minimum GATE length of PMOSML = 0.5
5681 0 INFO : metcap not inside met2
5684 0 W1MC Minimum METCAP width = 4
5687 0 W2MC Minimum dummy METCAP width = 0.5
5697 0 W3MC Maximum METCAP size = 30
5698 0 W1M2  Maximum MET2 width (capacitor bottom plate ) = 35
5701 0 S1MCMC Minimum METCAP spacing = 0.8
5703 0 S1M2M2 Minimum MET2 spacing (capacitor bottom plate) = 0.8
5707 0 S1MCV1 Minimum spacing between VIA1 and METCAP = 0.5
5711 0 S1MCV2 Minimum spacing between VIA2 and METCAP = 0.5
5716 0 S1V2V2  Minimum VIA2 spacing on MET2 bottom plate outside METCAP = 4
5720 0 S2V2V2  Minimum VIA2 spacing on METCAP = 3.5
5725 0 E1M2MC Minimum MET2 enclosure of METCAP = 1
5736 0 E1M2V1 Minimum MET2 enclosure of VIA1 (capacitor bottom plate) = 0.2
5739 0 E1M2V2 Minimum MET2 enclosure of VIA2 (capacitor bottom plate) = 0.2
5743 0 E1MCV2 Minimum METCAP enclosure of VIA2 = 0.5
5745 0 R1MC Minimum METCAP density [%] = 3
5748 0 R1V2 Minimum VIA2 density inside METCAP [%] = 1
5749 0 BAD1M1 MET1 under METCAP region is not allowed
5764 0 CMIM_G1: cmim device over active or passive device not allowed
5765 0 CPOLY_G1 PPLUS on CPOLY is not allowed
5766 0 CPOLY_G2 NPLUS on CPOLY is not allowed
5767 0 RPOLY1_R1 PPLUS on RPOLY1 is not allowed
5768 0 RPOLY1_R2 NPLUS on RPOLY1 is not allowed
5769 0 RPOLY2_R1 PPLUS on RPOLY2 is not allowed
5770 0 RPOLY2_R2 NPLUS on RPOLY2 is not allowed
5771 0 RPOLY2P_R1 PPLUS on RPOLY2P is not allowed
5772 0 RPOLY2P_R2 NPLUS on RPOLY2P is not allowed
5773 0 RPOLY2PH_R1 PPLUS on RPOLY2PH is not allowed
5774 0 RPOLY2PH_R2 NPLUS on RPOLY2PH is not allowed
5777 0 E1IPCT Minimum PPLUS enclosure of POLY2CON = 0.6
5778 0 E1IPCT Minimum PPLUS enclosure of POLY2CON = 0.6 missing pplus
5787 0 S1IPP2 Minimum PPLUS to RPOLYH spacing = 0.35
5789 0 RPOLYH_G2 Minimum high precision RPOLYH width = 2
5791 0 W4P2 Minimum RPOLYZ width = 0.8
5794 0 S4P2P2 Minimum RPOLYZ spacing = 0.75
5796 0 S4P2P2 Minimum RPOLYZ spacing = 0.75 notch
5799 0 E2IPCT Minimum PPLUS enclosure of POLY2CON = 0.6
5800 0 E2IPCT Minimum PPLUS enclosure of POLY2CON = 0.6 missing pplus
5809 0 S2IPP2 Minimum PPLUS to RPOLYZ spacing = 0.35
5811 0 RPOLYZ_G2 Minimum high precision RPOLYZ width = 2
6149 0 AMW0 Maximum METx width = 35 metal1
6151 0 AMW0 Maximum METx width = 35 metal2
6153 0 AMW0 Maximum METx width = 35 metal3
6155 0 AMW0 Maximum METx width = 35 metal4
6157 0 AMW1 Fixed slot width = 3 metal1
6160 0 AMW1 Fixed slot width = 3  metal1toolarge
6162 0 AMW1 Fixed slot width = 3 metal2
6165 0 AMW1 Fixed slot width = 3  metal2toolarge
6167 0 AMW1 Fixed slot width = 3 metal3
6170 0 AMW1 Fixed slot width = 3  metal3toolarge
6172 0 AMW1 Fixed slot width = 3 metal4
6175 0 AMW1 Fixed slot width = 3  metal4toolarge
6177 0 AML1 AM_L_2 Minimum slot length = 30 Maximum slot length = 300 metal1
6179 0 AML1 AM_L_2 Minimum slot length = 30 Maximum slot length = 300 metal2
6181 0 AML1 AM_L_2 Minimum slot length = 30 Maximum slot length = 300 metal3
6183 0 AML1 AM_L_2 Minimum slot length = 30 Maximum slot length = 300 metal4
6186 0 AMS1 Minimum spacing between two parallel slots = 10 metal1
6189 0 AMS1 Minimum spacing between two parallel slots = 10 metal2
6192 0 AMS1 Minimum spacing between two parallel slots = 10 metal3
6195 0 AMS1 Minimum spacing between two parallel slots = 10 metal4
6197 0 AMC1 Minimum slots spacing between neighbour layers  = 2 met1 met2 
6199 0 AMC1 Minimum slots spacing between neighbour layers  = 2 met2 met3 
6200 0 AMC1 Minimum slots spacing between neighbour layers  = 2 met1 met2 overlap 
6201 0 AMC1 Minimum slots spacing between neighbour layers  = 2 met2 met3 overlap 
6203 0 AMC1 Minimum slots spacing between neighbour layers  = 2 met3 met4 
6204 0 AMC1 Minimum slots spacing between neighbour layers  = 2 met3 met4 overlap 
6207 0 AMC2 AMC3 Minimum slot to inner metal edge spacing = 10 metal1
6210 0 AMC2 AMC3 Minimum slot to inner metal edge spacing = 10 metal2
6213 0 AMC2 AMC3 Minimum slot to inner metal edge spacing = 10 metal3
6216 0 AMC2 AMC3 Minimum slot to inner metal edge spacing = 10 metal4
6217 0 AM ERROR BAD SLOT: met1 slot outside met1
6218 0 AM ERROR BAD SLOT: met2 slot outside met2
6219 0 AM ERROR BAD SLOT: met3 slot outside met3
6220 0 AM ERROR BAD SLOT: met1 slot over cont
6221 0 AM ERROR BAD SLOT: met1 slot over via1
6222 0 AM ERROR BAD SLOT: met2 slot over via1
6223 0 AM ERROR BAD SLOT: met2 slot over via2
6224 0 AM ERROR BAD SLOT: met3 slot over via2
6225 0 AM ERROR BAD SLOT: met4 slot outside met4
6226 0 AM ERROR BAD SLOT: met4 slot over via3
6230 0 AMTW1 AMTL1 fixed with of dummy MTOP thin blocks 2.0 x 5.0 U
6232 0 AMTS2  Minimum MTOP feature to dummy MTOP block spacing = 2
6919 0 AMTS1 Maximum MTOP spacing when the width of one or both MTOP shapes is less than 10um = 10
7024 0 AMTS3 maximum met4 to met4 block spacing
7027 0  AMTS4 fixed met4 block spacing (checked min only 2.0 U)
7029 0 NWR001 NTUB overlapping KEPOUT is not allowed
7031 0 S1KONW Minimum NTUB spacing to KEPOUT or SFCDEF = 3
7032 0 AAR001 DIFF overlapping KEPOUT is not allowed
7034 0 S1AAKO Minimum DIFF spacing to KEPOUT or SFCDEF = 0.6
7035 0 XMR002 MIDOX overlapping KEPOUT is not allowed
7037 0 S1KOXM Minimum MIDOX spacing to KEPOUT or SFCDEF = 0.6
7038 0 P1R002 POLY1 overlapping KEPOUT is not allowed
7040 0 S1KOP1 Minimum POLY1 spacing to KEPOUT or SFCDEF = 0.45
7041 0 NSR001 NPLUS overlapping KEPOUT is not allowed
7043 0 S1KONS Minimum NPLUS spacing to KEPOUT or SFCDEF = 0.6
7044 0 PSR001 PPLUS overlapping KEPOUT is not allowed
7046 0 S1KOPS Minimum PPLUS spacing to KEPOUT or SFCDEF = 0.6
7047 0 HRR004 HRES overlapping KEPOUT is not allowed
7049 0 S1HRKO Minimum HRES spacing to KEPOUT or SFCDEF = 0.6
7050 0 P2R002 POLY2 overlapping KEPOUT is not allowed
7052 0 S1KOP2 Minimum POLY2 spacing to KEPOUT or SFCDEF = 0.6
7053 0 COR002 CONT overlapping KEPOUT is not allowed
7055 0 S1COKO Minimum CONT spacing to KEPOUT or SFCDEF = 0.4
7056 0 M1R002 MET1 overlapping KEPOUT is not allowed
7058 0 S1KOM1 Minimum MET1 spacing to KEPOUT or SFCDEF = 0.45
7059 0 V1R002 VIA1 overlapping KEPOUT is not allowed
7061 0 S1KOV1 Minimum VIA1 spacing to KEPOUT or SFCDEF = 0.45
7062 0 M2R002 MET2 overlapping KEPOUT is not allowed
7064 0 S1KOM2 0.5
7065 0 V2R002 VIA2 overlapping KEPOUT is not allowed
7067 0 S1KOV2 Minimum VIA2 spacing to KEPOUT or SFCDEF = 0.45
7068 0 M3R002 MET3 overlapping KEPOUT is not allowed
7070 0 S1KOM3 Minimum MET3 spacing to KEPOUT or SFCDEF = 0.6
7071 0 PAR002 PAD overlapping KEPOUT is not allowed
7073 0 S1KOPA Minimum PAD spacing to KEPOUT or SFCDEF (not shown) = 9
7074 0 LVR004 LVTDEF overlapping KEPOUT is not allowed
7076 0 S1KOLV Minimum LVTDEF spacing to KEPOUT or SFCDEF = 0.6
7077 0 MCR002 METCAP overlapping KEPOUT is not allowed
7079 0 S1MCKO Minimum METCAP spacing to KEPOUT or SFCDEF = 0.8
7080 0 V3R002 VIA3 overlapping KEPOUT is not allowed
7082 0 S1KOV3 Minimum VIA3 spacing to KEPOUT or SFCDEF = 0.45
7083 0 M4R002 MET4 overlapping KEPOUT is not allowed
7085 0 S1KOM4 Minimum MET4 spacing to KEPOUT or SFCDEF = 0.6
7088 0 Recommendation: Fixed RESTRM enclosure of RESDEF edge 0.1
7091 0 Recommendation: Fixed RESTRM enclosure of TUBDEF edge 0.1
7096 0 Warning: Illegal Layout Convention: RESDEF/TUBDEF missing RESTRM
7099 0 Warning: Illegal Layout Convention: RESTRM missing RESDEF
7101 0 ERC Warning: DIFF without any contact
7102 0 ERC Warning: Floating Poly1
7103 0 ERC Warning: Floating Poly2
7104 0 ERC Warning: Floating met1
7105 0 ERC Warning: Floating met2
7106 0 ERC Warning: Floating met3
7107 0 ERC Warning: Floating met4
7114 0 ERC Warning: possible Z Diode
7117 0 ERC Warning: Gates connected to VDD/VCC
7118 0 ERC Warning: Gates connected to VSS/GND
7159 0 ERC Warning: floating gate not connected to s/d, pad or resistor
7228 0 ERC Warning: Distance well taps > 50
7230 0 ERC Warning: illegal contact covering poly2 resistor
7232 0 ERC Warning: illegal contact covering poly2p resistor
7234 0 ERC Warning: illegal contact covering poly2ph resistor
7236 0 ERC Warning: illegal contact covering net_ndiff resistor
7238 0 ERC Warning: illegal contact covering net_pdiff resistor
7239 0 ERC Warning: illegal contact covering rpolyh resistor
7240 0 ERC Warning: illegal contact covering rpolyz resistor
7242 0 ERC Warning: illegal contact covering nwell resistor
7249 0 ERC Warning: illegal POLY2 touching rpoly2 resistor outside or bad cut layer
7250 0 ERC Warning: illegal poly2cut touching rpolyh resistor
7251 0 ERC Warning: illegal poly2cut touching rpolyz resistor
7255 0 ERC Warning: illegal NTUB touching rnwell resistor outside
7261 0 ERC Warning: illegal net_pdiff touching rdiffp resistor outside
7267 0 ERC Warning: illegal net_ndiff touching rdiffn resistor outside
7412 0 ERC Warning: Latchup rule LAT3 distance s/d diff ngate net_subtap > 20
7544 0 ERC Warning: Latchup rule LAT3 distance s/d diff pgate net_welltap > 20
7546 0 PWR001: FIMP outside SFCDEF will be removed and regenerated
7548 0 LDR001: NLDD outside SFCDEF will be removed and regenerated
7550 0  L2R001: NLDD50 outside SFCDEF will be removed and regenerated
7551 0 PYR001 PCOAT outside SFCDEF will be removed and regenerated
7553 0 Minimum PCOAT width = 15
7556 0 Minimum PCOAT spacing = 15
7557 0 REC002 PCOAT not multiple 45 degrees PCOAT
7560 0 W1BK Minimum PCOAT_black width = 2
7563 0 S1BKBK Minimum PCOAT_black spacing = 2.0
7565 0 S1BKPA Minimum PCOAT_blackto PAD spacing = 3.0
7568 0 S1BKSB Minimum PCOAT_black to CHIPEDGE spacing = 20.0
7571 0 GRCLEAR_COAT_W1 Minimum CLEAR_COAT width = 2
7574 0 GRCLEAR_COAT_S1 Minimum CLEAR_COAT spacing = 2.0
7576 0 GRCLEAR_COAT_S2 Minimum CLEAR_COAT to PAD spacing = 3.0
7579 0 GRCLEAR_COAT_E1 Minimum CLEAR_COAT to CHIPEDGE spacing = 20.0
7582 0 GRGREEN_COAT_W1 Minimum GREEN_COAT width = 2
7585 0 GRGREEN_COAT_S1 Minimum GREEN_COAT spacing = 2.0
7587 0 GRGREEN_COAT_S2 Minimum GREEN_COAT to PAD spacing = 3.0
7590 0 S1GNSB Minimum GREEN_COAT to CHIPEDGE spacing = 20.0
7593 0 GRRED_COAT_W1 Minimum RED_COAT width = 2
7596 0 GRRED_COAT_S1 Minimum RED_COAT spacing = 2.0
7598 0 GRRED_COAT_S2 Minimum RED_COAT to PAD spacing = 3.0
7601 0 GRRED_COAT_E1 Minimum RED_COAT to CHIPEDGE spacing = 20.0
7604 0 W1BU Minimum BLUE_COAT width = 2
7607 0 S1BUBU Minimum BLUE_COAT spacing = 2.0
7609 0 S1BUPA Minimum BLUE_COAT to PAD spacing = 3.0
7612 0 S1BUSB Minimum BLUE_COAT to CHIPEDGE spacing = 20.0
7754 0 GRCER001: DESIGN_DATA outside CHIPEDGE is not allowed!
7757 0 GRVTR010: VIATSV outside ANY_FILTER is not allowed, if any filter is used in the design
7761 0 GRRED_COAT_E2: Minimum CLEAR_COAT enclosure of RED_COAT = 2 U (enc.)
7762 0 GRRED_COAT_E2: Minimum CLEAR_COAT enclosure of RED_COAT = 2 U (straddle)
7763 0 GRRED_COAT_E2: Minimum CLEAR_COAT enclosure of RED_COAT = 2 U (butt.)
7766 0 GRRED_COAT_E3: Minimum RED_COAT enclosure of aperture = 2 U (enc.)
7767 0 GRRED_COAT_E3: Minimum RED_COAT enclosure of aperture = 2 U (straddle)
7768 0 GRRED_COAT_E3: Minimum RED_COAT enclosure of aperture = 2 U (butt.)
7769 0 GRRED_COAT_R1: RED_COAT outside CLEAR_COAT is not allowed
7773 0 GRBLUE_COAT_E2: Minimum CLEAR_COAT enclosure of BLUE_COAT = 2 U (enc.)
7774 0 GRBLUE_COAT_E2: Minimum CLEAR_COAT enclosure of BLUE_COAT = 2 U (straddle)
7775 0 GRBLUE_COAT_E2: Minimum CLEAR_COAT enclosure of BLUE_COAT = 2 U (butt.)
7778 0 GRBLUE_COAT_E3: Minimum BLUE_COAT enclosure of aperture = 2 U (enc.)
7779 0 GRBLUE_COAT_E3: Minimum BLUE_COAT enclosure of aperture = 2 U (straddle)
7780 0 GRBLUE_COAT_E3: Minimum BLUE_COAT enclosure of aperture = 2 U (butt.)
7781 0 GRBLUE_COAT_R1: BLUE_COAT outside CLEAR_COAT is not allowed
7785 0 GRGREEN_COAT_E2: Minimum CLEAR_COAT enclosure of GREEN_COAT = 2 U (enc.)
7786 0 GRGREEN_COAT_E2: Minimum CLEAR_COAT enclosure of GREEN_COAT = 2 U (straddle)
7787 0 GRGREEN_COAT_E2: Minimum CLEAR_COAT enclosure of GREEN_COAT = 2 U (butt.)
7790 0 GRGREEN_COAT_E3: Minimum GREEN_COAT enclosure of aperture = 2 U (enc.)
7791 0 GRGREEN_COAT_E3: Minimum GREEN_COAT enclosure of aperture = 2 U (straddle)
7792 0 GRGREEN_COAT_E3: Minimum GREEN_COAT enclosure of aperture = 2 U (butt.)
7793 0 GRGREEN_COAT_R1: GREEN_COAT outside CLEAR_COAT is not allowed
7796 0 GRFILTER_COMMON_W1: Minimum BLO1 width = 30 U
7799 0 GRFILTER_COMMON_W2: Minimum (BLO1 overlapping APERTURE) width = 80 U
7802 0 GRFILTER_COMMON_E2: Minimum BLO1 enclosure of VIATSV = 20 U (enc.)
7803 0 GRFILTER_COMMON_E2: Minimum BLO1 enclosure of VIATSV = 20 U (straddle)
7804 0 GRFILTER_COMMON_E2: Minimum BLO1 enclosure of VIATSV = 20 U (butt.)
7807 0 GRFILTER_COMMON_E3: Minimum BLO1 enclosure of aperture = 25 U (enc.)
7808 0 GRFILTER_COMMON_E3: Minimum BLO1 enclosure of aperture = 25 U (straddle)
7809 0 GRFILTER_COMMON_E3: Minimum BLO1 enclosure of aperture = 25 U (butt.)
7810 0 GRFILTER_COMMON_R1: BLO1 over PAD is not allowed
7813 0 GRFILTER_COMMON_E4: Minimum CHIPEDGE enclosure of BLO1 = 20 U (enc.)
7814 0 GRFILTER_COMMON_E4: Minimum CHIPEDGE enclosure of BLO1 = 20 U (straddle)
7815 0 GRFILTER_COMMON_E4: Minimum CHIPEDGE enclosure of BLO1 = 20 U (butt.)
7818 0 GRFILTER_COMMON_S2: Minimum BLO1 hole width (notch) = 45 U
7820 0 GRFILTER_COMMON_S2: Minimum BLO1 notch = 45 U
7822 0 GRFILTER_COMMON_S3: Minimum BLO1 to PAD spacing = 30 U
7824 0 GRFILTER_COMMON_E1: Minimum BLO1 enclosure of UVIRBL = 0 U
7826 0 GRFILTER_COMMON_E1: Minimum BLO1 enclosure of VISBL = 0 U
7828 0 GRFILTER_COMMON_E1: Minimum BLO1 enclosure of UVVISBL = 0 U
7830 0 GRFILTER_COMMON_E1: Minimum BLO1 enclosure of VISIRBL = 0 U
7832 0 GRFILTER_COMMON_E1: Minimum BLO1 enclosure of GREEN1 = 0 U
7834 0 GRFILTER_COMMON_E1: Minimum BLO1 enclosure of GREEN2 = 0 U
7836 0 GRFILTER_COMMON_E1: Minimum BLO1 enclosure of GREEN3 = 0 U
7838 0 GRFILTER_COMMON_E1: Minimum BLO1 enclosure of BLUE1 = 0 U
7840 0 GRFILTER_COMMON_E1: Minimum BLO1 enclosure of BLUE2 = 0 U
7842 0 GRFILTER_COMMON_E1: Minimum BLO1 enclosure of BLUE3 = 0 U
7844 0 GRFILTER_COMMON_E1: Minimum BLO1 enclosure of RED1 = 0 U
7846 0 GRFILTER_COMMON_E1: Minimum BLO1 enclosure of RED2 = 0 U
7848 0 GRFILTER_COMMON_E1: Minimum BLO1 enclosure of RED3 = 0 U
7850 0 GRFILTER_COMMON_E1: Minimum BLO1 enclosure of UVF = 0 U
7852 0 GRFILTER_COMMON_R2:  Overlapping different BLO2 and BLO1 layers is not allowed
7854 0 GRFILTER_COMMON_R2:  Overlapping different BLO3 and BLO1 layers is not allowed
7856 0 GRFILTER_COMMON_R2:  Overlapping different BLO4 and BLO1 layers is not allowed
7859 0 GRFILTER_COMMON_S1: Minimum BLO1 spacing = 30 U
7862 0 GRFILTER_OPTICAL_S1: Minimum BLO1 to (APERTURE not touching ANY_FILTER) spacing = 7 U
7865 0 GRFILTER_COMMON_W1: Minimum BLO2 width = 30 U
7868 0 GRFILTER_COMMON_W2: Minimum (BLO2 overlapping APERTURE) width = 80 U
7871 0 GRFILTER_COMMON_E2: Minimum BLO2 enclosure of VIATSV = 20 U (enc.)
7872 0 GRFILTER_COMMON_E2: Minimum BLO2 enclosure of VIATSV = 20 U (straddle)
7873 0 GRFILTER_COMMON_E2: Minimum BLO2 enclosure of VIATSV = 20 U (butt.)
7876 0 GRFILTER_COMMON_E3: Minimum BLO2 enclosure of aperture = 25 U (enc.)
7877 0 GRFILTER_COMMON_E3: Minimum BLO2 enclosure of aperture = 25 U (straddle)
7878 0 GRFILTER_COMMON_E3: Minimum BLO2 enclosure of aperture = 25 U (butt.)
7879 0 GRFILTER_COMMON_R1: BLO2 over PAD is not allowed
7882 0 GRFILTER_COMMON_E4: Minimum CHIPEDGE enclosure of BLO2 = 20 U (enc.)
7883 0 GRFILTER_COMMON_E4: Minimum CHIPEDGE enclosure of BLO2 = 20 U (straddle)
7884 0 GRFILTER_COMMON_E4: Minimum CHIPEDGE enclosure of BLO2 = 20 U (butt.)
7887 0 GRFILTER_COMMON_S2: Minimum BLO2 hole width (notch) = 45 U
7889 0 GRFILTER_COMMON_S2: Minimum BLO2 notch = 45 U
7891 0 GRFILTER_COMMON_S3: Minimum BLO2 to PAD spacing = 30 U
7893 0 GRFILTER_COMMON_E1: Minimum BLO2 enclosure of UVIRBL = 0 U
7895 0 GRFILTER_COMMON_E1: Minimum BLO2 enclosure of VISBL = 0 U
7897 0 GRFILTER_COMMON_E1: Minimum BLO2 enclosure of UVVISBL = 0 U
7899 0 GRFILTER_COMMON_E1: Minimum BLO2 enclosure of VISIRBL = 0 U
7901 0 GRFILTER_COMMON_E1: Minimum BLO2 enclosure of GREEN1 = 0 U
7903 0 GRFILTER_COMMON_E1: Minimum BLO2 enclosure of GREEN2 = 0 U
7905 0 GRFILTER_COMMON_E1: Minimum BLO2 enclosure of GREEN3 = 0 U
7907 0 GRFILTER_COMMON_E1: Minimum BLO2 enclosure of BLUE1 = 0 U
7909 0 GRFILTER_COMMON_E1: Minimum BLO2 enclosure of BLUE2 = 0 U
7911 0 GRFILTER_COMMON_E1: Minimum BLO2 enclosure of BLUE3 = 0 U
7913 0 GRFILTER_COMMON_E1: Minimum BLO2 enclosure of RED1 = 0 U
7915 0 GRFILTER_COMMON_E1: Minimum BLO2 enclosure of RED2 = 0 U
7917 0 GRFILTER_COMMON_E1: Minimum BLO2 enclosure of RED3 = 0 U
7919 0 GRFILTER_COMMON_E1: Minimum BLO2 enclosure of UVF = 0 U
7921 0 GRFILTER_COMMON_R2:  Overlapping different BLO3 and BLO2 layers is not allowed
7923 0 GRFILTER_COMMON_R2:  Overlapping different BLO4 and BLO2 layers is not allowed
7926 0 GRFILTER_COMMON_S1: Minimum BLO2 spacing = 30 U
7929 0 GRFILTER_OPTICAL_S1: Minimum BLO2 to (APERTURE not touching ANY_FILTER) spacing = 7 U
7932 0 GRFILTER_COMMON_W1: Minimum BLO3 width = 30 U
7935 0 GRFILTER_COMMON_W2: Minimum (BLO3 overlapping APERTURE) width = 80 U
7938 0 GRFILTER_COMMON_E2: Minimum BLO3 enclosure of VIATSV = 20 U (enc.)
7939 0 GRFILTER_COMMON_E2: Minimum BLO3 enclosure of VIATSV = 20 U (straddle)
7940 0 GRFILTER_COMMON_E2: Minimum BLO3 enclosure of VIATSV = 20 U (butt.)
7943 0 GRFILTER_COMMON_E3: Minimum BLO3 enclosure of aperture = 25 U (enc.)
7944 0 GRFILTER_COMMON_E3: Minimum BLO3 enclosure of aperture = 25 U (straddle)
7945 0 GRFILTER_COMMON_E3: Minimum BLO3 enclosure of aperture = 25 U (butt.)
7946 0 GRFILTER_COMMON_R1: BLO3 over PAD is not allowed
7949 0 GRFILTER_COMMON_E4: Minimum CHIPEDGE enclosure of BLO3 = 20 U (enc.)
7950 0 GRFILTER_COMMON_E4: Minimum CHIPEDGE enclosure of BLO3 = 20 U (straddle)
7951 0 GRFILTER_COMMON_E4: Minimum CHIPEDGE enclosure of BLO3 = 20 U (butt.)
7954 0 GRFILTER_COMMON_S2: Minimum BLO3 hole width (notch) = 45 U
7956 0 GRFILTER_COMMON_S2: Minimum BLO3 notch = 45 U
7958 0 GRFILTER_COMMON_S3: Minimum BLO3 to PAD spacing = 30 U
7960 0 GRFILTER_COMMON_E1: Minimum BLO3 enclosure of UVIRBL = 0 U
7962 0 GRFILTER_COMMON_E1: Minimum BLO3 enclosure of VISBL = 0 U
7964 0 GRFILTER_COMMON_E1: Minimum BLO3 enclosure of UVVISBL = 0 U
7966 0 GRFILTER_COMMON_E1: Minimum BLO3 enclosure of VISIRBL = 0 U
7968 0 GRFILTER_COMMON_E1: Minimum BLO3 enclosure of GREEN1 = 0 U
7970 0 GRFILTER_COMMON_E1: Minimum BLO3 enclosure of GREEN2 = 0 U
7972 0 GRFILTER_COMMON_E1: Minimum BLO3 enclosure of GREEN3 = 0 U
7974 0 GRFILTER_COMMON_E1: Minimum BLO3 enclosure of BLUE1 = 0 U
7976 0 GRFILTER_COMMON_E1: Minimum BLO3 enclosure of BLUE2 = 0 U
7978 0 GRFILTER_COMMON_E1: Minimum BLO3 enclosure of BLUE3 = 0 U
7980 0 GRFILTER_COMMON_E1: Minimum BLO3 enclosure of RED1 = 0 U
7982 0 GRFILTER_COMMON_E1: Minimum BLO3 enclosure of RED2 = 0 U
7984 0 GRFILTER_COMMON_E1: Minimum BLO3 enclosure of RED3 = 0 U
7986 0 GRFILTER_COMMON_E1: Minimum BLO3 enclosure of UVF = 0 U
7988 0 GRFILTER_COMMON_R2:  Overlapping different BLO4 and BLO3 layers is not allowed
7991 0 GRFILTER_COMMON_S1: Minimum BLO3 spacing = 30 U
7994 0 GRFILTER_OPTICAL_S1: Minimum BLO3 to (APERTURE not touching ANY_FILTER) spacing = 7 U
7997 0 GRFILTER_COMMON_W1: Minimum BLO4 width = 30 U
8000 0 GRFILTER_COMMON_W2: Minimum (BLO4 overlapping APERTURE) width = 80 U
8003 0 GRFILTER_COMMON_E2: Minimum BLO4 enclosure of VIATSV = 20 U (enc.)
8004 0 GRFILTER_COMMON_E2: Minimum BLO4 enclosure of VIATSV = 20 U (straddle)
8005 0 GRFILTER_COMMON_E2: Minimum BLO4 enclosure of VIATSV = 20 U (butt.)
8008 0 GRFILTER_COMMON_E3: Minimum BLO4 enclosure of aperture = 25 U (enc.)
8009 0 GRFILTER_COMMON_E3: Minimum BLO4 enclosure of aperture = 25 U (straddle)
8010 0 GRFILTER_COMMON_E3: Minimum BLO4 enclosure of aperture = 25 U (butt.)
8011 0 GRFILTER_COMMON_R1: BLO4 over PAD is not allowed
8014 0 GRFILTER_COMMON_E4: Minimum CHIPEDGE enclosure of BLO4 = 20 U (enc.)
8015 0 GRFILTER_COMMON_E4: Minimum CHIPEDGE enclosure of BLO4 = 20 U (straddle)
8016 0 GRFILTER_COMMON_E4: Minimum CHIPEDGE enclosure of BLO4 = 20 U (butt.)
8019 0 GRFILTER_COMMON_S2: Minimum BLO4 hole width (notch) = 45 U
8021 0 GRFILTER_COMMON_S2: Minimum BLO4 notch = 45 U
8023 0 GRFILTER_COMMON_S3: Minimum BLO4 to PAD spacing = 30 U
8025 0 GRFILTER_COMMON_E1: Minimum BLO4 enclosure of UVIRBL = 0 U
8027 0 GRFILTER_COMMON_E1: Minimum BLO4 enclosure of VISBL = 0 U
8029 0 GRFILTER_COMMON_E1: Minimum BLO4 enclosure of UVVISBL = 0 U
8031 0 GRFILTER_COMMON_E1: Minimum BLO4 enclosure of VISIRBL = 0 U
8033 0 GRFILTER_COMMON_E1: Minimum BLO4 enclosure of GREEN1 = 0 U
8035 0 GRFILTER_COMMON_E1: Minimum BLO4 enclosure of GREEN2 = 0 U
8037 0 GRFILTER_COMMON_E1: Minimum BLO4 enclosure of GREEN3 = 0 U
8039 0 GRFILTER_COMMON_E1: Minimum BLO4 enclosure of BLUE1 = 0 U
8041 0 GRFILTER_COMMON_E1: Minimum BLO4 enclosure of BLUE2 = 0 U
8043 0 GRFILTER_COMMON_E1: Minimum BLO4 enclosure of BLUE3 = 0 U
8045 0 GRFILTER_COMMON_E1: Minimum BLO4 enclosure of RED1 = 0 U
8047 0 GRFILTER_COMMON_E1: Minimum BLO4 enclosure of RED2 = 0 U
8049 0 GRFILTER_COMMON_E1: Minimum BLO4 enclosure of RED3 = 0 U
8051 0 GRFILTER_COMMON_E1: Minimum BLO4 enclosure of UVF = 0 U
8054 0 GRFILTER_COMMON_S1: Minimum BLO4 spacing = 30 U
8057 0 GRFILTER_OPTICAL_S1: Minimum BLO4 to (APERTURE not touching ANY_FILTER) spacing = 7 U
8060 0 GRFILTER_REGULAR_W1: Minimum UVIRBL width = 30 U
8063 0 GRFILTER_REGULAR_W2: Minimum (UVIRBL overlapping APERTURE) width = 80 U
8066 0 GRFILTER_REGULAR_E1: Minimum UVIRBL enclosure of VIATSV = 20 U (encl.)
8067 0 GRFILTER_REGULAR_E1: Minimum UVIRBL enclosure of VIATSV = 20 U (straddle)
8070 0 GRFILTER_REGULAR_E2: Minimum UVIRBL enclosure of APERTURE = 25 U (encl.)
8071 0 GRFILTER_REGULAR_E2: Minimum UVIRBL enclosure of APERTURE = 25 U (straddle)
8072 0 GRFILTER_REGULAR_R1: UVIRBL over PAD is not allowed
8075 0 GRFILTER_REGULAR_E3: Minimum CHIPEDGE enclosure of UVIRBL = 20 U (enc.)
8076 0 GRFILTER_REGULAR_E3: Minimum CHIPEDGE enclosure of UVIRBL = 20 U (straddle)
8077 0 GRFILTER_REGULAR_E3: Minimum CHIPEDGE enclosure of UVIRBL = 20 U (butt.)
8080 0 GRFILTER_REGULAR_S2: Minimum UVIRBL hole width (notch) = 45 U
8082 0 GRFILTER_REGULAR_S2: Minimum UVIRBL notch  = 45 U
8084 0 GRFILTER_REGULAR_S3: Minimum UVIRBL to PAD spacing = 30 U
8086 0 GRFILTER_REGULAR_R2:  Overlapping different VISBL and UVIRBL layers is not allowed
8088 0 GRFILTER_REGULAR_R2:  Overlapping different UVVISBL and UVIRBL layers is not allowed
8090 0 GRFILTER_REGULAR_R2:  Overlapping different VISIRBL and UVIRBL layers is not allowed
8092 0 GRFILTER_REGULAR_R2:  Overlapping different GREEN1 and UVIRBL layers is not allowed
8094 0 GRFILTER_REGULAR_R2:  Overlapping different GREEN2 and UVIRBL layers is not allowed
8096 0 GRFILTER_REGULAR_R2:  Overlapping different GREEN3 and UVIRBL layers is not allowed
8098 0 GRFILTER_REGULAR_R2:  Overlapping different BLUE1 and UVIRBL layers is not allowed
8100 0 GRFILTER_REGULAR_R2:  Overlapping different BLUE2 and UVIRBL layers is not allowed
8102 0 GRFILTER_REGULAR_R2:  Overlapping different BLUE3 and UVIRBL layers is not allowed
8104 0 GRFILTER_REGULAR_R2:  Overlapping different RED1 and UVIRBL layers is not allowed
8106 0 GRFILTER_REGULAR_R2:  Overlapping different RED2 and UVIRBL layers is not allowed
8108 0 GRFILTER_REGULAR_R2:  Overlapping different RED3 and UVIRBL layers is not allowed
8110 0 GRFILTER_REGULAR_R2:  Overlapping different UVF and UVIRBL layers is not allowed
8113 0 GRFILTER_REGULAR_S1: Minimum UVIRBL spacing = 29 U
8116 0 GRFILTER_OPTICAL_S1: Minimum UVIRBL to (APERTURE not touching ANY_FILTER) spacing = 7 U
8119 0 GRFILTER_REGULAR_W1: Minimum VISBL width = 30 U
8122 0 GRFILTER_REGULAR_W2: Minimum (VISBL overlapping APERTURE) width = 80 U
8125 0 GRFILTER_REGULAR_E1: Minimum VISBL enclosure of VIATSV = 20 U (encl.)
8126 0 GRFILTER_REGULAR_E1: Minimum VISBL enclosure of VIATSV = 20 U (straddle)
8129 0 GRFILTER_REGULAR_E2: Minimum VISBL enclosure of APERTURE = 25 U (encl.)
8130 0 GRFILTER_REGULAR_E2: Minimum VISBL enclosure of APERTURE = 25 U (straddle)
8131 0 GRFILTER_REGULAR_R1: VISBL over PAD is not allowed
8134 0 GRFILTER_REGULAR_E3: Minimum CHIPEDGE enclosure of VISBL = 20 U (enc.)
8135 0 GRFILTER_REGULAR_E3: Minimum CHIPEDGE enclosure of VISBL = 20 U (straddle)
8136 0 GRFILTER_REGULAR_E3: Minimum CHIPEDGE enclosure of VISBL = 20 U (butt.)
8139 0 GRFILTER_REGULAR_S2: Minimum VISBL hole width (notch) = 45 U
8141 0 GRFILTER_REGULAR_S2: Minimum VISBL notch  = 45 U
8143 0 GRFILTER_REGULAR_S3: Minimum VISBL to PAD spacing = 30 U
8145 0 GRFILTER_REGULAR_R2:  Overlapping different UVVISBL and VISBL layers is not allowed
8147 0 GRFILTER_REGULAR_R2:  Overlapping different VISIRBL and VISBL layers is not allowed
8149 0 GRFILTER_REGULAR_R2:  Overlapping different GREEN1 and VISBL layers is not allowed
8151 0 GRFILTER_REGULAR_R2:  Overlapping different GREEN2 and VISBL layers is not allowed
8153 0 GRFILTER_REGULAR_R2:  Overlapping different GREEN3 and VISBL layers is not allowed
8155 0 GRFILTER_REGULAR_R2:  Overlapping different BLUE1 and VISBL layers is not allowed
8157 0 GRFILTER_REGULAR_R2:  Overlapping different BLUE2 and VISBL layers is not allowed
8159 0 GRFILTER_REGULAR_R2:  Overlapping different BLUE3 and VISBL layers is not allowed
8161 0 GRFILTER_REGULAR_R2:  Overlapping different RED1 and VISBL layers is not allowed
8163 0 GRFILTER_REGULAR_R2:  Overlapping different RED2 and VISBL layers is not allowed
8165 0 GRFILTER_REGULAR_R2:  Overlapping different RED3 and VISBL layers is not allowed
8167 0 GRFILTER_REGULAR_R2:  Overlapping different UVF and VISBL layers is not allowed
8170 0 GRFILTER_REGULAR_S1: Minimum VISBL spacing = 29 U
8173 0 GRFILTER_OPTICAL_S1: Minimum VISBL to (APERTURE not touching ANY_FILTER) spacing = 7 U
8176 0 GRFILTER_REGULAR_W1: Minimum UVVISBL width = 30 U
8179 0 GRFILTER_REGULAR_W2: Minimum (UVVISBL overlapping APERTURE) width = 80 U
8182 0 GRFILTER_REGULAR_E1: Minimum UVVISBL enclosure of VIATSV = 20 U (encl.)
8183 0 GRFILTER_REGULAR_E1: Minimum UVVISBL enclosure of VIATSV = 20 U (straddle)
8186 0 GRFILTER_REGULAR_E2: Minimum UVVISBL enclosure of APERTURE = 25 U (encl.)
8187 0 GRFILTER_REGULAR_E2: Minimum UVVISBL enclosure of APERTURE = 25 U (straddle)
8188 0 GRFILTER_REGULAR_R1: UVVISBL over PAD is not allowed
8191 0 GRFILTER_REGULAR_E3: Minimum CHIPEDGE enclosure of UVVISBL = 20 U (enc.)
8192 0 GRFILTER_REGULAR_E3: Minimum CHIPEDGE enclosure of UVVISBL = 20 U (straddle)
8193 0 GRFILTER_REGULAR_E3: Minimum CHIPEDGE enclosure of UVVISBL = 20 U (butt.)
8196 0 GRFILTER_REGULAR_S2: Minimum UVVISBL hole width (notch) = 45 U
8198 0 GRFILTER_REGULAR_S2: Minimum UVVISBL notch  = 45 U
8200 0 GRFILTER_REGULAR_S3: Minimum UVVISBL to PAD spacing = 30 U
8202 0 GRFILTER_REGULAR_R2:  Overlapping different VISIRBL and UVVISBL layers is not allowed
8204 0 GRFILTER_REGULAR_R2:  Overlapping different GREEN1 and UVVISBL layers is not allowed
8206 0 GRFILTER_REGULAR_R2:  Overlapping different GREEN2 and UVVISBL layers is not allowed
8208 0 GRFILTER_REGULAR_R2:  Overlapping different GREEN3 and UVVISBL layers is not allowed
8210 0 GRFILTER_REGULAR_R2:  Overlapping different BLUE1 and UVVISBL layers is not allowed
8212 0 GRFILTER_REGULAR_R2:  Overlapping different BLUE2 and UVVISBL layers is not allowed
8214 0 GRFILTER_REGULAR_R2:  Overlapping different BLUE3 and UVVISBL layers is not allowed
8216 0 GRFILTER_REGULAR_R2:  Overlapping different RED1 and UVVISBL layers is not allowed
8218 0 GRFILTER_REGULAR_R2:  Overlapping different RED2 and UVVISBL layers is not allowed
8220 0 GRFILTER_REGULAR_R2:  Overlapping different RED3 and UVVISBL layers is not allowed
8222 0 GRFILTER_REGULAR_R2:  Overlapping different UVF and UVVISBL layers is not allowed
8225 0 GRFILTER_REGULAR_S1: Minimum UVVISBL spacing = 29 U
8228 0 GRFILTER_OPTICAL_S1: Minimum UVVISBL to (APERTURE not touching ANY_FILTER) spacing = 7 U
8231 0 GRFILTER_REGULAR_W1: Minimum VISIRBL width = 30 U
8234 0 GRFILTER_REGULAR_W2: Minimum (VISIRBL overlapping APERTURE) width = 80 U
8237 0 GRFILTER_REGULAR_E1: Minimum VISIRBL enclosure of VIATSV = 20 U (encl.)
8238 0 GRFILTER_REGULAR_E1: Minimum VISIRBL enclosure of VIATSV = 20 U (straddle)
8241 0 GRFILTER_REGULAR_E2: Minimum VISIRBL enclosure of APERTURE = 25 U (encl.)
8242 0 GRFILTER_REGULAR_E2: Minimum VISIRBL enclosure of APERTURE = 25 U (straddle)
8243 0 GRFILTER_REGULAR_R1: VISIRBL over PAD is not allowed
8246 0 GRFILTER_REGULAR_E3: Minimum CHIPEDGE enclosure of VISIRBL = 20 U (enc.)
8247 0 GRFILTER_REGULAR_E3: Minimum CHIPEDGE enclosure of VISIRBL = 20 U (straddle)
8248 0 GRFILTER_REGULAR_E3: Minimum CHIPEDGE enclosure of VISIRBL = 20 U (butt.)
8251 0 GRFILTER_REGULAR_S2: Minimum VISIRBL hole width (notch) = 45 U
8253 0 GRFILTER_REGULAR_S2: Minimum VISIRBL notch  = 45 U
8255 0 GRFILTER_REGULAR_S3: Minimum VISIRBL to PAD spacing = 30 U
8257 0 GRFILTER_REGULAR_R2:  Overlapping different GREEN1 and VISIRBL layers is not allowed
8259 0 GRFILTER_REGULAR_R2:  Overlapping different GREEN2 and VISIRBL layers is not allowed
8261 0 GRFILTER_REGULAR_R2:  Overlapping different GREEN3 and VISIRBL layers is not allowed
8263 0 GRFILTER_REGULAR_R2:  Overlapping different BLUE1 and VISIRBL layers is not allowed
8265 0 GRFILTER_REGULAR_R2:  Overlapping different BLUE2 and VISIRBL layers is not allowed
8267 0 GRFILTER_REGULAR_R2:  Overlapping different BLUE3 and VISIRBL layers is not allowed
8269 0 GRFILTER_REGULAR_R2:  Overlapping different RED1 and VISIRBL layers is not allowed
8271 0 GRFILTER_REGULAR_R2:  Overlapping different RED2 and VISIRBL layers is not allowed
8273 0 GRFILTER_REGULAR_R2:  Overlapping different RED3 and VISIRBL layers is not allowed
8275 0 GRFILTER_REGULAR_R2:  Overlapping different UVF and VISIRBL layers is not allowed
8278 0 GRFILTER_REGULAR_S1: Minimum VISIRBL spacing = 29 U
8281 0 GRFILTER_OPTICAL_S1: Minimum VISIRBL to (APERTURE not touching ANY_FILTER) spacing = 7 U
8284 0 GRFILTER_REGULAR_W1: Minimum GREEN1 width = 30 U
8287 0 GRFILTER_REGULAR_W2: Minimum (GREEN1 overlapping APERTURE) width = 80 U
8290 0 GRFILTER_REGULAR_E1: Minimum GREEN1 enclosure of VIATSV = 20 U (encl.)
8291 0 GRFILTER_REGULAR_E1: Minimum GREEN1 enclosure of VIATSV = 20 U (straddle)
8294 0 GRFILTER_REGULAR_E2: Minimum GREEN1 enclosure of APERTURE = 25 U (encl.)
8295 0 GRFILTER_REGULAR_E2: Minimum GREEN1 enclosure of APERTURE = 25 U (straddle)
8296 0 GRFILTER_REGULAR_R1: GREEN1 over PAD is not allowed
8299 0 GRFILTER_REGULAR_E3: Minimum CHIPEDGE enclosure of GREEN1 = 20 U (enc.)
8300 0 GRFILTER_REGULAR_E3: Minimum CHIPEDGE enclosure of GREEN1 = 20 U (straddle)
8301 0 GRFILTER_REGULAR_E3: Minimum CHIPEDGE enclosure of GREEN1 = 20 U (butt.)
8304 0 GRFILTER_REGULAR_S2: Minimum GREEN1 hole width (notch) = 45 U
8306 0 GRFILTER_REGULAR_S2: Minimum GREEN1 notch  = 45 U
8308 0 GRFILTER_REGULAR_S3: Minimum GREEN1 to PAD spacing = 30 U
8310 0 GRFILTER_REGULAR_R2:  Overlapping different GREEN2 and GREEN1 layers is not allowed
8312 0 GRFILTER_REGULAR_R2:  Overlapping different GREEN3 and GREEN1 layers is not allowed
8314 0 GRFILTER_REGULAR_R2:  Overlapping different BLUE1 and GREEN1 layers is not allowed
8316 0 GRFILTER_REGULAR_R2:  Overlapping different BLUE2 and GREEN1 layers is not allowed
8318 0 GRFILTER_REGULAR_R2:  Overlapping different BLUE3 and GREEN1 layers is not allowed
8320 0 GRFILTER_REGULAR_R2:  Overlapping different RED1 and GREEN1 layers is not allowed
8322 0 GRFILTER_REGULAR_R2:  Overlapping different RED2 and GREEN1 layers is not allowed
8324 0 GRFILTER_REGULAR_R2:  Overlapping different RED3 and GREEN1 layers is not allowed
8326 0 GRFILTER_REGULAR_R2:  Overlapping different UVF and GREEN1 layers is not allowed
8329 0 GRFILTER_REGULAR_S1: Minimum GREEN1 spacing = 29 U
8332 0 GRFILTER_OPTICAL_S1: Minimum GREEN1 to (APERTURE not touching ANY_FILTER) spacing = 7 U
8335 0 GRFILTER_REGULAR_W1: Minimum GREEN2 width = 30 U
8338 0 GRFILTER_REGULAR_W2: Minimum (GREEN2 overlapping APERTURE) width = 80 U
8341 0 GRFILTER_REGULAR_E1: Minimum GREEN2 enclosure of VIATSV = 20 U (encl.)
8342 0 GRFILTER_REGULAR_E1: Minimum GREEN2 enclosure of VIATSV = 20 U (straddle)
8345 0 GRFILTER_REGULAR_E2: Minimum GREEN2 enclosure of APERTURE = 25 U (encl.)
8346 0 GRFILTER_REGULAR_E2: Minimum GREEN2 enclosure of APERTURE = 25 U (straddle)
8347 0 GRFILTER_REGULAR_R1: GREEN2 over PAD is not allowed
8350 0 GRFILTER_REGULAR_E3: Minimum CHIPEDGE enclosure of GREEN2 = 20 U (enc.)
8351 0 GRFILTER_REGULAR_E3: Minimum CHIPEDGE enclosure of GREEN2 = 20 U (straddle)
8352 0 GRFILTER_REGULAR_E3: Minimum CHIPEDGE enclosure of GREEN2 = 20 U (butt.)
8355 0 GRFILTER_REGULAR_S2: Minimum GREEN2 hole width (notch) = 45 U
8357 0 GRFILTER_REGULAR_S2: Minimum GREEN2 notch  = 45 U
8359 0 GRFILTER_REGULAR_S3: Minimum GREEN2 to PAD spacing = 30 U
8361 0 GRFILTER_REGULAR_R2:  Overlapping different GREEN3 and GREEN2 layers is not allowed
8363 0 GRFILTER_REGULAR_R2:  Overlapping different BLUE1 and GREEN2 layers is not allowed
8365 0 GRFILTER_REGULAR_R2:  Overlapping different BLUE2 and GREEN2 layers is not allowed
8367 0 GRFILTER_REGULAR_R2:  Overlapping different BLUE3 and GREEN2 layers is not allowed
8369 0 GRFILTER_REGULAR_R2:  Overlapping different RED1 and GREEN2 layers is not allowed
8371 0 GRFILTER_REGULAR_R2:  Overlapping different RED2 and GREEN2 layers is not allowed
8373 0 GRFILTER_REGULAR_R2:  Overlapping different RED3 and GREEN2 layers is not allowed
8375 0 GRFILTER_REGULAR_R2:  Overlapping different UVF and GREEN2 layers is not allowed
8378 0 GRFILTER_REGULAR_S1: Minimum GREEN2 spacing = 29 U
8381 0 GRFILTER_OPTICAL_S1: Minimum GREEN2 to (APERTURE not touching ANY_FILTER) spacing = 7 U
8384 0 GRFILTER_REGULAR_W1: Minimum GREEN3 width = 30 U
8387 0 GRFILTER_REGULAR_W2: Minimum (GREEN3 overlapping APERTURE) width = 80 U
8390 0 GRFILTER_REGULAR_E1: Minimum GREEN3 enclosure of VIATSV = 20 U (encl.)
8391 0 GRFILTER_REGULAR_E1: Minimum GREEN3 enclosure of VIATSV = 20 U (straddle)
8394 0 GRFILTER_REGULAR_E2: Minimum GREEN3 enclosure of APERTURE = 25 U (encl.)
8395 0 GRFILTER_REGULAR_E2: Minimum GREEN3 enclosure of APERTURE = 25 U (straddle)
8396 0 GRFILTER_REGULAR_R1: GREEN3 over PAD is not allowed
8399 0 GRFILTER_REGULAR_E3: Minimum CHIPEDGE enclosure of GREEN3 = 20 U (enc.)
8400 0 GRFILTER_REGULAR_E3: Minimum CHIPEDGE enclosure of GREEN3 = 20 U (straddle)
8401 0 GRFILTER_REGULAR_E3: Minimum CHIPEDGE enclosure of GREEN3 = 20 U (butt.)
8404 0 GRFILTER_REGULAR_S2: Minimum GREEN3 hole width (notch) = 45 U
8406 0 GRFILTER_REGULAR_S2: Minimum GREEN3 notch  = 45 U
8408 0 GRFILTER_REGULAR_S3: Minimum GREEN3 to PAD spacing = 30 U
8410 0 GRFILTER_REGULAR_R2:  Overlapping different BLUE1 and GREEN3 layers is not allowed
8412 0 GRFILTER_REGULAR_R2:  Overlapping different BLUE2 and GREEN3 layers is not allowed
8414 0 GRFILTER_REGULAR_R2:  Overlapping different BLUE3 and GREEN3 layers is not allowed
8416 0 GRFILTER_REGULAR_R2:  Overlapping different RED1 and GREEN3 layers is not allowed
8418 0 GRFILTER_REGULAR_R2:  Overlapping different RED2 and GREEN3 layers is not allowed
8420 0 GRFILTER_REGULAR_R2:  Overlapping different RED3 and GREEN3 layers is not allowed
8422 0 GRFILTER_REGULAR_R2:  Overlapping different UVF and GREEN3 layers is not allowed
8425 0 GRFILTER_REGULAR_S1: Minimum GREEN3 spacing = 29 U
8428 0 GRFILTER_OPTICAL_S1: Minimum GREEN3 to (APERTURE not touching ANY_FILTER) spacing = 7 U
8431 0 GRFILTER_REGULAR_W1: Minimum BLUE1 width = 30 U
8434 0 GRFILTER_REGULAR_W2: Minimum (BLUE1 overlapping APERTURE) width = 80 U
8437 0 GRFILTER_REGULAR_E1: Minimum BLUE1 enclosure of VIATSV = 20 U (encl.)
8438 0 GRFILTER_REGULAR_E1: Minimum BLUE1 enclosure of VIATSV = 20 U (straddle)
8441 0 GRFILTER_REGULAR_E2: Minimum BLUE1 enclosure of APERTURE = 25 U (encl.)
8442 0 GRFILTER_REGULAR_E2: Minimum BLUE1 enclosure of APERTURE = 25 U (straddle)
8443 0 GRFILTER_REGULAR_R1: BLUE1 over PAD is not allowed
8446 0 GRFILTER_REGULAR_E3: Minimum CHIPEDGE enclosure of BLUE1 = 20 U (enc.)
8447 0 GRFILTER_REGULAR_E3: Minimum CHIPEDGE enclosure of BLUE1 = 20 U (straddle)
8448 0 GRFILTER_REGULAR_E3: Minimum CHIPEDGE enclosure of BLUE1 = 20 U (butt.)
8451 0 GRFILTER_REGULAR_S2: Minimum BLUE1 hole width (notch) = 45 U
8453 0 GRFILTER_REGULAR_S2: Minimum BLUE1 notch  = 45 U
8455 0 GRFILTER_REGULAR_S3: Minimum BLUE1 to PAD spacing = 30 U
8457 0 GRFILTER_REGULAR_R2:  Overlapping different BLUE2 and BLUE1 layers is not allowed
8459 0 GRFILTER_REGULAR_R2:  Overlapping different BLUE3 and BLUE1 layers is not allowed
8461 0 GRFILTER_REGULAR_R2:  Overlapping different RED1 and BLUE1 layers is not allowed
8463 0 GRFILTER_REGULAR_R2:  Overlapping different RED2 and BLUE1 layers is not allowed
8465 0 GRFILTER_REGULAR_R2:  Overlapping different RED3 and BLUE1 layers is not allowed
8467 0 GRFILTER_REGULAR_R2:  Overlapping different UVF and BLUE1 layers is not allowed
8470 0 GRFILTER_REGULAR_S1: Minimum BLUE1 spacing = 29 U
8473 0 GRFILTER_OPTICAL_S1: Minimum BLUE1 to (APERTURE not touching ANY_FILTER) spacing = 7 U
8476 0 GRFILTER_REGULAR_W1: Minimum BLUE2 width = 30 U
8479 0 GRFILTER_REGULAR_W2: Minimum (BLUE2 overlapping APERTURE) width = 80 U
8482 0 GRFILTER_REGULAR_E1: Minimum BLUE2 enclosure of VIATSV = 20 U (encl.)
8483 0 GRFILTER_REGULAR_E1: Minimum BLUE2 enclosure of VIATSV = 20 U (straddle)
8486 0 GRFILTER_REGULAR_E2: Minimum BLUE2 enclosure of APERTURE = 25 U (encl.)
8487 0 GRFILTER_REGULAR_E2: Minimum BLUE2 enclosure of APERTURE = 25 U (straddle)
8488 0 GRFILTER_REGULAR_R1: BLUE2 over PAD is not allowed
8491 0 GRFILTER_REGULAR_E3: Minimum CHIPEDGE enclosure of BLUE2 = 20 U (enc.)
8492 0 GRFILTER_REGULAR_E3: Minimum CHIPEDGE enclosure of BLUE2 = 20 U (straddle)
8493 0 GRFILTER_REGULAR_E3: Minimum CHIPEDGE enclosure of BLUE2 = 20 U (butt.)
8496 0 GRFILTER_REGULAR_S2: Minimum BLUE2 hole width (notch) = 45 U
8498 0 GRFILTER_REGULAR_S2: Minimum BLUE2 notch  = 45 U
8500 0 GRFILTER_REGULAR_S3: Minimum BLUE2 to PAD spacing = 30 U
8502 0 GRFILTER_REGULAR_R2:  Overlapping different BLUE3 and BLUE2 layers is not allowed
8504 0 GRFILTER_REGULAR_R2:  Overlapping different RED1 and BLUE2 layers is not allowed
8506 0 GRFILTER_REGULAR_R2:  Overlapping different RED2 and BLUE2 layers is not allowed
8508 0 GRFILTER_REGULAR_R2:  Overlapping different RED3 and BLUE2 layers is not allowed
8510 0 GRFILTER_REGULAR_R2:  Overlapping different UVF and BLUE2 layers is not allowed
8513 0 GRFILTER_REGULAR_S1: Minimum BLUE2 spacing = 29 U
8516 0 GRFILTER_OPTICAL_S1: Minimum BLUE2 to (APERTURE not touching ANY_FILTER) spacing = 7 U
8519 0 GRFILTER_REGULAR_W1: Minimum BLUE3 width = 30 U
8522 0 GRFILTER_REGULAR_W2: Minimum (BLUE3 overlapping APERTURE) width = 80 U
8525 0 GRFILTER_REGULAR_E1: Minimum BLUE3 enclosure of VIATSV = 20 U (encl.)
8526 0 GRFILTER_REGULAR_E1: Minimum BLUE3 enclosure of VIATSV = 20 U (straddle)
8529 0 GRFILTER_REGULAR_E2: Minimum BLUE3 enclosure of APERTURE = 25 U (encl.)
8530 0 GRFILTER_REGULAR_E2: Minimum BLUE3 enclosure of APERTURE = 25 U (straddle)
8531 0 GRFILTER_REGULAR_R1: BLUE3 over PAD is not allowed
8534 0 GRFILTER_REGULAR_E3: Minimum CHIPEDGE enclosure of BLUE3 = 20 U (enc.)
8535 0 GRFILTER_REGULAR_E3: Minimum CHIPEDGE enclosure of BLUE3 = 20 U (straddle)
8536 0 GRFILTER_REGULAR_E3: Minimum CHIPEDGE enclosure of BLUE3 = 20 U (butt.)
8539 0 GRFILTER_REGULAR_S2: Minimum BLUE3 hole width (notch) = 45 U
8541 0 GRFILTER_REGULAR_S2: Minimum BLUE3 notch  = 45 U
8543 0 GRFILTER_REGULAR_S3: Minimum BLUE3 to PAD spacing = 30 U
8545 0 GRFILTER_REGULAR_R2:  Overlapping different RED1 and BLUE3 layers is not allowed
8547 0 GRFILTER_REGULAR_R2:  Overlapping different RED2 and BLUE3 layers is not allowed
8549 0 GRFILTER_REGULAR_R2:  Overlapping different RED3 and BLUE3 layers is not allowed
8551 0 GRFILTER_REGULAR_R2:  Overlapping different UVF and BLUE3 layers is not allowed
8554 0 GRFILTER_REGULAR_S1: Minimum BLUE3 spacing = 29 U
8557 0 GRFILTER_OPTICAL_S1: Minimum BLUE3 to (APERTURE not touching ANY_FILTER) spacing = 7 U
8560 0 GRFILTER_REGULAR_W1: Minimum RED1 width = 30 U
8563 0 GRFILTER_REGULAR_W2: Minimum (RED1 overlapping APERTURE) width = 80 U
8566 0 GRFILTER_REGULAR_E1: Minimum RED1 enclosure of VIATSV = 20 U (encl.)
8567 0 GRFILTER_REGULAR_E1: Minimum RED1 enclosure of VIATSV = 20 U (straddle)
8570 0 GRFILTER_REGULAR_E2: Minimum RED1 enclosure of APERTURE = 25 U (encl.)
8571 0 GRFILTER_REGULAR_E2: Minimum RED1 enclosure of APERTURE = 25 U (straddle)
8572 0 GRFILTER_REGULAR_R1: RED1 over PAD is not allowed
8575 0 GRFILTER_REGULAR_E3: Minimum CHIPEDGE enclosure of RED1 = 20 U (enc.)
8576 0 GRFILTER_REGULAR_E3: Minimum CHIPEDGE enclosure of RED1 = 20 U (straddle)
8577 0 GRFILTER_REGULAR_E3: Minimum CHIPEDGE enclosure of RED1 = 20 U (butt.)
8580 0 GRFILTER_REGULAR_S2: Minimum RED1 hole width (notch) = 45 U
8582 0 GRFILTER_REGULAR_S2: Minimum RED1 notch  = 45 U
8584 0 GRFILTER_REGULAR_S3: Minimum RED1 to PAD spacing = 30 U
8586 0 GRFILTER_REGULAR_R2:  Overlapping different RED2 and RED1 layers is not allowed
8588 0 GRFILTER_REGULAR_R2:  Overlapping different RED3 and RED1 layers is not allowed
8590 0 GRFILTER_REGULAR_R2:  Overlapping different UVF and RED1 layers is not allowed
8593 0 GRFILTER_REGULAR_S1: Minimum RED1 spacing = 29 U
8596 0 GRFILTER_OPTICAL_S1: Minimum RED1 to (APERTURE not touching ANY_FILTER) spacing = 7 U
8599 0 GRFILTER_REGULAR_W1: Minimum RED2 width = 30 U
8602 0 GRFILTER_REGULAR_W2: Minimum (RED2 overlapping APERTURE) width = 80 U
8605 0 GRFILTER_REGULAR_E1: Minimum RED2 enclosure of VIATSV = 20 U (encl.)
8606 0 GRFILTER_REGULAR_E1: Minimum RED2 enclosure of VIATSV = 20 U (straddle)
8609 0 GRFILTER_REGULAR_E2: Minimum RED2 enclosure of APERTURE = 25 U (encl.)
8610 0 GRFILTER_REGULAR_E2: Minimum RED2 enclosure of APERTURE = 25 U (straddle)
8611 0 GRFILTER_REGULAR_R1: RED2 over PAD is not allowed
8614 0 GRFILTER_REGULAR_E3: Minimum CHIPEDGE enclosure of RED2 = 20 U (enc.)
8615 0 GRFILTER_REGULAR_E3: Minimum CHIPEDGE enclosure of RED2 = 20 U (straddle)
8616 0 GRFILTER_REGULAR_E3: Minimum CHIPEDGE enclosure of RED2 = 20 U (butt.)
8619 0 GRFILTER_REGULAR_S2: Minimum RED2 hole width (notch) = 45 U
8621 0 GRFILTER_REGULAR_S2: Minimum RED2 notch  = 45 U
8623 0 GRFILTER_REGULAR_S3: Minimum RED2 to PAD spacing = 30 U
8625 0 GRFILTER_REGULAR_R2:  Overlapping different RED3 and RED2 layers is not allowed
8627 0 GRFILTER_REGULAR_R2:  Overlapping different UVF and RED2 layers is not allowed
8630 0 GRFILTER_REGULAR_S1: Minimum RED2 spacing = 29 U
8633 0 GRFILTER_OPTICAL_S1: Minimum RED2 to (APERTURE not touching ANY_FILTER) spacing = 7 U
8636 0 GRFILTER_REGULAR_W1: Minimum RED3 width = 30 U
8639 0 GRFILTER_REGULAR_W2: Minimum (RED3 overlapping APERTURE) width = 80 U
8642 0 GRFILTER_REGULAR_E1: Minimum RED3 enclosure of VIATSV = 20 U (encl.)
8643 0 GRFILTER_REGULAR_E1: Minimum RED3 enclosure of VIATSV = 20 U (straddle)
8646 0 GRFILTER_REGULAR_E2: Minimum RED3 enclosure of APERTURE = 25 U (encl.)
8647 0 GRFILTER_REGULAR_E2: Minimum RED3 enclosure of APERTURE = 25 U (straddle)
8648 0 GRFILTER_REGULAR_R1: RED3 over PAD is not allowed
8651 0 GRFILTER_REGULAR_E3: Minimum CHIPEDGE enclosure of RED3 = 20 U (enc.)
8652 0 GRFILTER_REGULAR_E3: Minimum CHIPEDGE enclosure of RED3 = 20 U (straddle)
8653 0 GRFILTER_REGULAR_E3: Minimum CHIPEDGE enclosure of RED3 = 20 U (butt.)
8656 0 GRFILTER_REGULAR_S2: Minimum RED3 hole width (notch) = 45 U
8658 0 GRFILTER_REGULAR_S2: Minimum RED3 notch  = 45 U
8660 0 GRFILTER_REGULAR_S3: Minimum RED3 to PAD spacing = 30 U
8662 0 GRFILTER_REGULAR_R2:  Overlapping different UVF and RED3 layers is not allowed
8665 0 GRFILTER_REGULAR_S1: Minimum RED3 spacing = 29 U
8668 0 GRFILTER_OPTICAL_S1: Minimum RED3 to (APERTURE not touching ANY_FILTER) spacing = 7 U
8671 0 GRFILTER_REGULAR_W1: Minimum UVF width = 30 U
8674 0 GRFILTER_REGULAR_W2: Minimum (UVF overlapping APERTURE) width = 80 U
8677 0 GRFILTER_REGULAR_E1: Minimum UVF enclosure of VIATSV = 20 U (encl.)
8678 0 GRFILTER_REGULAR_E1: Minimum UVF enclosure of VIATSV = 20 U (straddle)
8681 0 GRFILTER_REGULAR_E2: Minimum UVF enclosure of APERTURE = 25 U (encl.)
8682 0 GRFILTER_REGULAR_E2: Minimum UVF enclosure of APERTURE = 25 U (straddle)
8683 0 GRFILTER_REGULAR_R1: UVF over PAD is not allowed
8686 0 GRFILTER_REGULAR_E3: Minimum CHIPEDGE enclosure of UVF = 20 U (enc.)
8687 0 GRFILTER_REGULAR_E3: Minimum CHIPEDGE enclosure of UVF = 20 U (straddle)
8688 0 GRFILTER_REGULAR_E3: Minimum CHIPEDGE enclosure of UVF = 20 U (butt.)
8691 0 GRFILTER_REGULAR_S2: Minimum UVF hole width (notch) = 45 U
8693 0 GRFILTER_REGULAR_S2: Minimum UVF notch  = 45 U
8695 0 GRFILTER_REGULAR_S3: Minimum UVF to PAD spacing = 30 U
8698 0 GRFILTER_REGULAR_S1: Minimum UVF spacing = 29 U
8701 0 GRFILTER_OPTICAL_S1: Minimum UVF to (APERTURE not touching ANY_FILTER) spacing = 7 U
8703 0 GRFILTER_BLACK_W1: Minimum FILTER_BLACK width = 30 U
8706 0 GRFILTER_BLACK_S1: Minimum FILTER_BLACK spacing = 30 U
8709 0 GRFILTER_BLACK_S2: Minimum FILTER_BLACK hole width (notch) = 45 U
8711 0 GRFILTER_BLACK_S2: Minimum FILTER_BLACK notch = 45 U
8713 0 GRFILTER_BLACK_S3: Minimum FILTER_BLACK to PAD spacing = 30 U
8714 0 GRFILTER_BLACK_S4: Fixed FILTER_BLACK to aperture spacing = 6.7 U  < 
8725 0 GRFILTER_BLACK_S4: Fixed FILTER_BLACK to aperture spacing = 6.7 U (straddle)
8729 0 GRFILTER_BLACK_R1:  FILTER_BLACK over UVIRBL over aperture is not allowed
8733 0 GRFILTER_BLACK_R1:  FILTER_BLACK over VISBL over aperture is not allowed
8737 0 GRFILTER_BLACK_R1:  FILTER_BLACK over UVVISBL over aperture is not allowed
8741 0 GRFILTER_BLACK_R1:  FILTER_BLACK over VISIRBL over aperture is not allowed
8745 0 GRFILTER_BLACK_R1:  FILTER_BLACK over GREEN1 over aperture is not allowed
8749 0 GRFILTER_BLACK_R1:  FILTER_BLACK over GREEN2 over aperture is not allowed
8753 0 GRFILTER_BLACK_R1:  FILTER_BLACK over GREEN3 over aperture is not allowed
8757 0 GRFILTER_BLACK_R1:  FILTER_BLACK over BLUE1 over aperture is not allowed
8761 0 GRFILTER_BLACK_R1:  FILTER_BLACK over BLUE2 over aperture is not allowed
8765 0 GRFILTER_BLACK_R1:  FILTER_BLACK over BLUE3 over aperture is not allowed
8769 0 GRFILTER_BLACK_R1:  FILTER_BLACK over RED1 over aperture is not allowed
8773 0 GRFILTER_BLACK_R1:  FILTER_BLACK over RED2 over aperture is not allowed
8777 0 GRFILTER_BLACK_R1:  FILTER_BLACK over RED3 over aperture is not allowed
8781 0 GRFILTER_BLACK_R1:  FILTER_BLACK over UVF over aperture is not allowed
8785 0 GRFILTER_BLACK_R1:  FILTER_BLACK over BLO1 over aperture is not allowed
8789 0 GRFILTER_BLACK_R1:  FILTER_BLACK over BLO2 over aperture is not allowed
8793 0 GRFILTER_BLACK_R1:  FILTER_BLACK over BLO3 over aperture is not allowed
8797 0 GRFILTER_BLACK_R1:  FILTER_BLACK over BLO4 over aperture is not allowed
8801 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of UVIRBL = 20 U (enc.)
8804 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of UVIRBL = 20 U (straddle)
8805 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of UVIRBL = 20 U (butt.)
8809 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of VISBL = 20 U (enc.)
8812 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of VISBL = 20 U (straddle)
8813 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of VISBL = 20 U (butt.)
8817 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of UVVISBL = 20 U (enc.)
8820 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of UVVISBL = 20 U (straddle)
8821 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of UVVISBL = 20 U (butt.)
8825 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of VISIRBL = 20 U (enc.)
8828 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of VISIRBL = 20 U (straddle)
8829 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of VISIRBL = 20 U (butt.)
8833 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of GREEN1 = 20 U (enc.)
8836 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of GREEN1 = 20 U (straddle)
8837 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of GREEN1 = 20 U (butt.)
8841 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of GREEN2 = 20 U (enc.)
8844 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of GREEN2 = 20 U (straddle)
8845 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of GREEN2 = 20 U (butt.)
8849 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of GREEN3 = 20 U (enc.)
8852 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of GREEN3 = 20 U (straddle)
8853 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of GREEN3 = 20 U (butt.)
8857 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of BLUE1 = 20 U (enc.)
8860 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of BLUE1 = 20 U (straddle)
8861 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of BLUE1 = 20 U (butt.)
8865 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of BLUE2 = 20 U (enc.)
8868 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of BLUE2 = 20 U (straddle)
8869 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of BLUE2 = 20 U (butt.)
8873 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of BLUE3 = 20 U (enc.)
8876 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of BLUE3 = 20 U (straddle)
8877 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of BLUE3 = 20 U (butt.)
8881 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of RED1 = 20 U (enc.)
8884 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of RED1 = 20 U (straddle)
8885 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of RED1 = 20 U (butt.)
8889 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of RED2 = 20 U (enc.)
8892 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of RED2 = 20 U (straddle)
8893 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of RED2 = 20 U (butt.)
8897 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of RED3 = 20 U (enc.)
8900 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of RED3 = 20 U (straddle)
8901 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of RED3 = 20 U (butt.)
8905 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of UVF = 20 U (enc.)
8908 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of UVF = 20 U (straddle)
8909 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of UVF = 20 U (butt.)
8913 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of BLO1 = 20 U (enc.)
8916 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of BLO1 = 20 U (straddle)
8917 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of BLO1 = 20 U (butt.)
8921 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of BLO2 = 20 U (enc.)
8924 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of BLO2 = 20 U (straddle)
8925 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of BLO2 = 20 U (butt.)
8929 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of BLO3 = 20 U (enc.)
8932 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of BLO3 = 20 U (straddle)
8933 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of BLO3 = 20 U (butt.)
8937 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of BLO4 = 20 U (enc.)
8940 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of BLO4 = 20 U (straddle)
8941 0 GRFILTER_BLACK_E1: Minimum FILTER_BLACK enclosure of BLO4 = 20 U (butt.)
8942 0 GRFILTER_BLACK_R2: FILTER_BLACK over PAD is not allowed
8945 0 GRFILTER_BLACK_E2: Minimum FILTER_BLACK enclosure of VIATSV = 20 U (enc.)
8946 0 GRFILTER_BLACK_E2: Minimum FILTER_BLACK enclosure of VIATSV = 20 U (straddle)
8947 0 GRFILTER_BLACK_E2: Minimum FILTER_BLACK enclosure of VIATSV = 20 U (butt.)
8950 0 GRFILTER_BLACK_E3: Minimum CHIPEDGE enclosure of FILTER_BLACK = 20 U (enc.)
8951 0 GRFILTER_BLACK_E3: Minimum CHIPEDGE enclosure of FILTER_BLACK = 20 U (straddle)
8952 0 GRFILTER_BLACK_E3: Minimum CHIPEDGE enclosure of FILTER_BLACK = 20 U (butt.)
8965 0 GRFILTER_OPTICAL_R1: (BLO1 sized 900 U) must cover CHIPEDGE
8968 0 GRFILTER_OPTICAL_R1: (BLO1 sized 900 U) must cover die-area
8978 0 GRFILTER_OPTICAL_R1: (BLO2 sized 900 U) must cover CHIPEDGE
8981 0 GRFILTER_OPTICAL_R1: (BLO2 sized 900 U) must cover die-area
8991 0 GRFILTER_OPTICAL_R1: (BLO3 sized 900 U) must cover CHIPEDGE
8994 0 GRFILTER_OPTICAL_R1: (BLO3 sized 900 U) must cover die-area
9004 0 GRFILTER_OPTICAL_R1: (BLO4 sized 900 U) must cover CHIPEDGE
9007 0 GRFILTER_OPTICAL_R1: (BLO4 sized 900 U) must cover die-area
9017 0 GRFILTER_OPTICAL_R1: (UVIRBL sized 900 U) must cover CHIPEDGE
9020 0 GRFILTER_OPTICAL_R1: (UVIRBL sized 900 U) must cover die-area
9030 0 GRFILTER_OPTICAL_R1: (VISBL sized 900 U) must cover CHIPEDGE
9033 0 GRFILTER_OPTICAL_R1: (VISBL sized 900 U) must cover die-area
9043 0 GRFILTER_OPTICAL_R1: (UVVISBL sized 900 U) must cover CHIPEDGE
9046 0 GRFILTER_OPTICAL_R1: (UVVISBL sized 900 U) must cover die-area
9056 0 GRFILTER_OPTICAL_R1: (VISIRBL sized 900 U) must cover CHIPEDGE
9059 0 GRFILTER_OPTICAL_R1: (VISIRBL sized 900 U) must cover die-area
9069 0 GRFILTER_OPTICAL_R1: (GREEN1 sized 900 U) must cover CHIPEDGE
9072 0 GRFILTER_OPTICAL_R1: (GREEN1 sized 900 U) must cover die-area
9082 0 GRFILTER_OPTICAL_R1: (GREEN2 sized 900 U) must cover CHIPEDGE
9085 0 GRFILTER_OPTICAL_R1: (GREEN2 sized 900 U) must cover die-area
9095 0 GRFILTER_OPTICAL_R1: (GREEN3 sized 900 U) must cover CHIPEDGE
9098 0 GRFILTER_OPTICAL_R1: (GREEN3 sized 900 U) must cover die-area
9108 0 GRFILTER_OPTICAL_R1: (BLUE1 sized 900 U) must cover CHIPEDGE
9111 0 GRFILTER_OPTICAL_R1: (BLUE1 sized 900 U) must cover die-area
9121 0 GRFILTER_OPTICAL_R1: (BLUE2 sized 900 U) must cover CHIPEDGE
9124 0 GRFILTER_OPTICAL_R1: (BLUE2 sized 900 U) must cover die-area
9134 0 GRFILTER_OPTICAL_R1: (BLUE3 sized 900 U) must cover CHIPEDGE
9137 0 GRFILTER_OPTICAL_R1: (BLUE3 sized 900 U) must cover die-area
9147 0 GRFILTER_OPTICAL_R1: (RED1 sized 900 U) must cover CHIPEDGE
9150 0 GRFILTER_OPTICAL_R1: (RED1 sized 900 U) must cover die-area
9160 0 GRFILTER_OPTICAL_R1: (RED2 sized 900 U) must cover CHIPEDGE
9163 0 GRFILTER_OPTICAL_R1: (RED2 sized 900 U) must cover die-area
9173 0 GRFILTER_OPTICAL_R1: (RED3 sized 900 U) must cover CHIPEDGE
9176 0 GRFILTER_OPTICAL_R1: (RED3 sized 900 U) must cover die-area
9186 0 GRFILTER_OPTICAL_R1: (UVF sized 900 U) must cover CHIPEDGE
9189 0 GRFILTER_OPTICAL_R1: (UVF sized 900 U) must cover die-area
9191 0 GRS1AAVT: Minimum VIATSV to DIFF spacing = 30 U
9192 0 GRVTR001: DIFF overlapping VIATSV is not allowed
9194 0 GRS1P1VT: Minimum VIATSV to POLY1 spacing = 30 U
9195 0 GRVTR002: POLY1 overlapping VIATSV is not allowed
9197 0 GRS1CTVT:  Minimum VIATSV to CONT spacing = 7 U
9198 0 GRVTR004: CONT Overlapping VIATSV is not allowed
9200 0 GRE1M1VT: Minimum MET1 enclosure of VIATSV = 15 U
9201 0 GRE1M1VT: Minimum MET1 enclosure of VIATSV = 15 U; VIATSV outside M1
9204 0 GRS1M1VT:  Minimum VIATSV to M1 (different net) = 20 U
9205 0 GRVTR010:  VIATSV outside M1 is not allowed
9207 0 GRE1M2VT: Minimum MET2 enclosure of VIATSV = 15 U
9208 0 GRE1M2VT: Minimum MET2 enclosure of VIATSV = 15 U; VIATSV outside M2
9211 0 GRS1M2VT:  Minimum VIATSV to M2 (different net) = 20 U
9212 0 GRVTR011:  VIATSV outside M2 is not allowed
9214 0 GRE1M3VT: Minimum MET3 enclosure of VIATSV = 15 U
9215 0 GRE1M3VT: Minimum MET3 enclosure of VIATSV = 15 U; VIATSV outside M3
9218 0 GRS1M3VT:  Minimum VIATSV to M3 (different net) = 20 U
9219 0 GRVTR012:  VIATSV outside M3 is not allowed
9221 0 GRE1M4VT: Minimum MET4 enclosure of VIATSV = 15 U
9222 0 GRE1M4VT: Minimum MET4 enclosure of VIATSV = 15 U; VIATSV outside M4
9225 0 GRS1M4VT:  Minimum VIATSV to M4 (different net) = 20 U
9226 0 GRVTR013:  VIATSV outside M4 is not allowed
9228 0 GRE1MTVT: Minimum METTSV enclosure of VIATSV = 15 U
9229 0 GRE1MTVT: Minimum METTSV enclosure of VIATSV = 15 U; VIATSV outside METTSV
9230 0 GRE1MTVT: Minimum METTSV enclosure of VIATSV = 15 U (straddle) 
9232 0 GRS1V1VT:  Minimum VIATSV to VIA1 spacing = 7 U
9233 0 GRVTR005: VIA1 overlapping  VIATSV is not allowed
9235 0 GRS1V2VT:  Minimum VIATSV to VIA2 spacing = 7 U
9236 0 GRVTR006: VIA2 overlapping  VIATSV is not allowed
9238 0 GRS1V3VT:  Minimum VIATSV to VIA3 spacing = 7 U
9239 0 GRVTR007: VIA3 overlapping  VIATSV is not allowed
9241 0 GRS1PAVT:  Minimum PAD to VIATSV spacing = 40 U
9242 0 GRVTR008: PAD overlapping  VIATSV is not allowed
9244 0 GRS1P2VT:  Minimum VIATSV to POLY2 spacing = 30 U
9245 0 GRVTR003: POLY2 overlapping  VIATSV is not allowed
9253 0 GRW1VT: Fixed diameter of VIATSV = 80 U
9257 0 GRW1VT: Fixed diameter of VIATSV = 80 U (inside notches present)
9260 0 GRS1VTVT: Minimum VIATSV spacing = 180 U
9263 0 GRE1CEVT: Minimum CHIPEDGE enclosure of VIATSV
9274 0 GRVTR014: VIATSV global density (must be <= 1.6%)  FAILS!!
9289 0 GRW2VT: Maximum TSV_ARRAY width = 300 U
9293 0 GRS3VTVT: Minumum VIATSV to TSV_ARRAY spacing( opposite only) = 5000 U
9295 0 GRS3VTVT: Minumum VIATSV to TSV_ARRAY spacing( opposite only) = 5000 U
9299 0 GRS2VTVT: Maximum VIATSV inside TSV_ARRAY = 500 U
9301 0 GRW1MT: Minimum METTSV width = 15 U
9304 0 GRS1MTMT: Minimum METTSV spacing = 15 U
9316 0 GRMTR001: METTSV global density (must be >= 30%)  FAILS!!
9318 0 GRW1PT: Minimum PADTSV width = 15 U
9321 0 GRW1PT: Minimum PADTSV width = 15U
9324 0 GRS1PTPT: Minimum PADTSV spacing = 15 U
9326 0 GRS1PTVT: Minimum PADTSV to VIATSV spacing = 80 U
9329 0 GRE1MTPT: Minimum MTTSV enclosure of PADTSV = 8 U
9330 0 GRE1MTPT: Minimum MTTSV enclosure of PADTSV = 8 U; PADTSV straddle MTTSV
9331 0 GRE1MTPT: Minimum MTTSV enclosure of PADTSV = 8 U; PADTSV outside MTTSV
9332 0 GRVTR009: PADTSV overlapping VIATSV not allowed
9338 0 BAD_PDIFF_MULTCONN_ERC
9343 0 BAD_NDIFF_MULTCONN_ERC
9350 0 AR1_error_gate: AR1: Maximum ratio of floating POLY1 edge area to connected GATE area = 200
9352 0 AR2_error_gate: AR2: Maximum ratio of floating MET1 edge area to connected GATE area = 400
9354 0 AR3_error_gate: AR3: Maximum ratio of floating MET2 edge area to connected GATE area = 400
9356 0 AR4_error_gate: AR4: Maximum ratio of floating MET3 edge area to connected GATE area = 400
9358 0 AR5_error_gate: AR5: Maximum ratio of floating MET4 edge area to connected GATE area = 400
9359 0 rpoly1_g1_pres1_wexp: RPOLY1_G1: Minimum number of RPOLY1 squares = 5
9360 0 rpoly2_g1_pres_wexp: RPOLY2_G1: Minimum number of RPOLY2 squares = 5
9361 0 rpoly2p_g1_presp_wexp: RPOLY2P_G1: Minimum number of RPOLY2P squares = 5
9362 0 rpoly2ph_g1_presph_wexp: RPOLY2PH_G1: Minimum number of RPOLY2PH squares = 5
9363 0 rnwell_g1_nwres_wexp: RNWELL_G1: Minimum number of RNWELL squares = 5
9364 0 rpolyh_g1_presh_wexp: RPOLYH_G1: Minimum number of RPOLYH squares = 5
9365 0 rpolyh_g1_presz_wexp: RPOLYZ_G1: Minimum number of RPOLYZ squares = 3.75
9366 0 G01P1_net_poly1con: G01P1 Maximum ratio of POLY2 area to connected CONT area = 18000
9367 0 G01P2_net_poly2con: G01P2 Maximum ratio of POLY2 area to connected CONT area = 22000
9375 0 CBR1 PAD met2 not connected to met1
9376 0 CBR1 PAD met3 not connected to met2
9377 0 CBR1 PAD met4 not connected to met3
9379 0 ERC Warning: Internal spiral met3 short
9381 0 ERC Warning: Internal spiral met2 short
9385 0 ERC Warning: spiral may be shorted by external met2
9389 0 ERC Warning: spiral may be shorted by external met3
9391 0 ERC Warning: Internal spiral met4 short
9395 0 ERC Warning: spiral may be shorted by external met4
9396 0 spiral_open_spiral_term22: ERC Warning : This spiral is open
9397 0 # INFO: C35B4/C35B3 ASSURA DRC DECK (REV9 DATE 26-Apr-2011) Last modified 07-Sept-2016 #
