0 0 dataAuditErrors
350 0 DEVICE Error: Illegal nmosh device
798 0 Process Modules : PHDNWA850 not available for this process module
802 0 Process Modules : PHDNWB850 not available for this process module
804 0 Version od SBD5 obsolte or missing
812 0 Process Modules : SBD5 not available for this process module
1288 0 ERC Warning : Name of Spiral not identified
1289 0 ERC Warning : INDDEF does not define a correct spiral or is not valid for this process
1306 0 ERC Warning : illegal layer under spiral
1319 0 ERC Warning : Each INDDEF shape must be marked with a single INDDEF text label
1321 0 ERC Warning : multiple text on INDEF
1324 0 Error: METRES overlapping CONT or VIAx
1328 0 Error: MET1RES overlapping CONT or VIA1
1332 0 Error: MET2RES overlapping VIA1 or VIA2
1336 0 Error: MET3RES overlapping VIA2 or VIA3
1339 0 Error: MET4RES overlapping VIA3
1351 0 Error: MET1 resistors (shorts) must be rectangular
1353 0 Error: Number of MET1 resistor terminals != 2
1364 0 Error: MET2 resistors (shorts) must be rectangular
1366 0 Error: Number of MET2 resistor terminals != 2
1377 0 Error: MET3 resistors (shorts) must be rectangular
1379 0 Error: Number of MET3 resistor terminals != 2
1390 0 Error: MET4 resistors (shorts) must be rectangular
1392 0 Error: Number of MET4 resistor terminals != 2
1402 0 RVIA1 Definition layer: does not open all via conncetion, is shorted
1405 0 RVIA1 Definition layer: truncates via1, device shorted
1406 0 RVIA1 Definition layer: does not define a device
1410 0 RVIA1 Definition layer: over METRES
1417 0 RVIA2 Definition layer: does not open all via conncetion, is shorted
1420 0 RVIA2 Definition layer: truncates via2, device shorted
1421 0 RVIA2 Definition layer : does not define a device
1425 0 RVIA2 Definition layer: over METRES
1433 0 RVIA3 Definition layer: does not open all via conncetion, is shorted
1436 0 RVIA3 Definition layer: truncates via3, device shorted
1437 0 RVIA3 Definition layer : does not define a device
1441 0 RVIA3 Definition layer: over METRES
1566 0 ERROR : POLY1 pin outside poly1
1567 0 ERROR : MET1 pin outside met1
1568 0 ERROR : MET2 pin outside met2
1569 0 ERROR: PADTSV pin outside METTSV
1571 0 ERROR : MET3 pin outside met3
1573 0 ERROR : MET4 pin outside met4
1574 0 ERROR : PAD pin outside pad metal
3214 0 # INFO: Set -resimulate_extracted- Switch for QRC! #
3216 0 # C35B4 ENG - 183 Rev9 (Last updated 26-Apr-2017 12:48) #
3517 0 malformed device NMOSH_device
3518 0 malformed device NMOSMH_device
3519 0 malformed device NMOS30M_device
3520 0 malformed device NMOS18T_device
3521 0 malformed device ESDPD12_device
3522 0 malformed device ESDPD18_device
3523 0 malformed device ESDPD26_device
3524 0 malformed device ESDPD30_device
3525 0 malformed device ESDFDN5_device
3526 0 malformed device ESDGCN5_device
3527 0 malformed device ESDFDP5_device
3528 0 malformed device ESDGCP5_device
3529 0 malformed device RNWELL_device
3530 0 malformed device RDIFFP_device
3531 0 malformed device RPOLY2_PSUB_device
3532 0 malformed device RPOLY2_NTUB_device
3533 0 malformed device RPOLY2PH_PSUB_device
3534 0 malformed device RPOLY2PH_NTUB_device
3535 0 malformed device RPOLYH_PSUB_device
3536 0 malformed device RPOLYH_NTUB_device
3537 0 malformed device RPOLY1_PSUB_device
3538 0 malformed device RPOLY1_NTUB_device
3539 0 malformed device PFUSE_device
3540 0 malformed device tsv_dev
3541 0 malformed device LAT2_device
3542 0 malformed device VERT10_device
3543 0 malformed device CPOLY_PSUB_device
3544 0 malformed device CPOLY_NTUB_device
3545 0 malformed device CVAR_device
3546 0 malformed device PROBE_device
3547 0 malformed device NMOSRF_device
3548 0 malformed device PMOSRF_device
3549 0 malformed device CPOLYRF_device
3550 0 malformed device RPOLY2RF_device
3551 0 malformed device RPOLYHRF_device
3552 0 malformed device SP014S300D_device
3553 0 malformed device SP020S180D_device
3554 0 malformed device SP026S200D_device
3555 0 malformed device SP037S180D_device
3556 0 malformed device SP047S180D_device
3557 0 malformed device SP050S155D_device
3558 0 malformed device SP090S155D_device
4078 0 unstable device for SP090S155D_device_Device_100
4079 0 unpreserved device SP090S155D_device_Device_100
4080 0 unstable device for SP050S155D_device_Device_99
4081 0 unpreserved device SP050S155D_device_Device_99
4082 0 unstable device for SP047S180D_device_Device_98
4083 0 unpreserved device SP047S180D_device_Device_98
4084 0 unstable device for SP037S180D_device_Device_97
4085 0 unpreserved device SP037S180D_device_Device_97
4086 0 unstable device for SP026S200D_device_Device_96
4087 0 unpreserved device SP026S200D_device_Device_96
4088 0 unstable device for SP020S180D_device_Device_95
4089 0 unpreserved device SP020S180D_device_Device_95
4090 0 unstable device for SP014S300D_device_Device_94
4091 0 unpreserved device SP014S300D_device_Device_94
4092 0 unstable device for RPOLYHRF_device_RES_93
4093 0 unpreserved device RPOLYHRF_device_RES_93
4094 0 unstable device for RPOLY2RF_device_RES_92
4095 0 unpreserved device RPOLY2RF_device_RES_92
4096 0 unstable device for CPOLYRF_device_CAP_91
4097 0 unpreserved device CPOLYRF_device_CAP_91
4098 0 unstable device for PMOSRF_device_Device_90
4099 0 unpreserved device PMOSRF_device_Device_90
4100 0 unstable device for NMOSRF_device_Device_89
4101 0 unpreserved device NMOSRF_device_Device_89
4102 0 unstable device for PROBE_device_Device_88
4103 0 unpreserved device PROBE_device_Device_88
4104 0 unstable device for CPMIM_device_Device_87
4105 0 unpreserved device CPMIM_device_Device_87
4106 0 unstable device for CMIM_device_no_cpmim_Device_86
4107 0 unpreserved device CMIM_device_no_cpmim_Device_86
4108 0 unstable device for CVAR_device_Device_85
4109 0 unpreserved device CVAR_device_Device_85
4110 0 unstable device for CPOLY_NTUB_device_CAP_84
4111 0 unpreserved device CPOLY_NTUB_device_CAP_84
4112 0 unstable device for CPOLY_PSUB_device_CAP_83
4113 0 unpreserved device CPOLY_PSUB_device_CAP_83
4114 0 unstable device for VERT10_device_BJT_82
4115 0 unpreserved device VERT10_device_BJT_82
4116 0 unstable device for VERT3_device_Device_81
4117 0 unpreserved device VERT3_device_Device_81
4118 0 unstable device for LAT2_device_Device_80
4119 0 unpreserved device LAT2_device_Device_80
4120 0 unstable device for tsv_dev_Device_79
4121 0 unpreserved device tsv_dev_Device_79
4122 0 unstable device for RVIA3_device_RES_78
4123 0 unpreserved device RVIA3_device_RES_78
4124 0 unstable device for RVIA2_device_RES_77
4125 0 unpreserved device RVIA2_device_RES_77
4126 0 unstable device for RVIA1_device_RES_76
4127 0 unpreserved device RVIA1_device_RES_76
4128 0 unstable device for RMET4_device_RES_75
4129 0 unpreserved device RMET4_device_RES_75
4130 0 unstable device for RMET3_device_RES_74
4131 0 unpreserved device RMET3_device_RES_74
4132 0 unstable device for RMET2_device_RES_73
4133 0 unpreserved device RMET2_device_RES_73
4134 0 unstable device for RMET1_device_RES_72
4135 0 unpreserved device RMET1_device_RES_72
4136 0 unstable device for PFUSE_device_RES_71
4137 0 unpreserved device PFUSE_device_RES_71
4138 0 unstable device for RPOLY1_NTUB_device_RES_70
4139 0 unpreserved device RPOLY1_NTUB_device_RES_70
4140 0 unstable device for RPOLY1_PSUB_device_RES_69
4141 0 unpreserved device RPOLY1_PSUB_device_RES_69
4142 0 unstable device for RPOLYZ_NTUB_device_Device_68
4143 0 unpreserved device RPOLYZ_NTUB_device_Device_68
4144 0 unstable device for RPOLYZ_PSUB_device_Device_67
4145 0 unpreserved device RPOLYZ_PSUB_device_Device_67
4146 0 unstable device for RPOLYH_NTUB_device_RES_66
4147 0 unpreserved device RPOLYH_NTUB_device_RES_66
4148 0 unstable device for RPOLYH_PSUB_device_RES_65
4149 0 unpreserved device RPOLYH_PSUB_device_RES_65
4150 0 unstable device for RPOLY2PH_NTUB_device_RES_64
4151 0 unpreserved device RPOLY2PH_NTUB_device_RES_64
4152 0 unstable device for RPOLY2PH_PSUB_device_RES_63
4153 0 unpreserved device RPOLY2PH_PSUB_device_RES_63
4154 0 unstable device for RPOLY2P_NTUB_device_Device_62
4155 0 unpreserved device RPOLY2P_NTUB_device_Device_62
4156 0 unstable device for RPOLY2P_PSUB_device_Device_61
4157 0 unpreserved device RPOLY2P_PSUB_device_Device_61
4158 0 unstable device for RPOLY2_NTUB_device_RES_60
4159 0 unpreserved device RPOLY2_NTUB_device_RES_60
4160 0 unstable device for RPOLY2_PSUB_device_RES_59
4161 0 unpreserved device RPOLY2_PSUB_device_RES_59
4162 0 unstable device for RDIFFN_device_RES_58
4163 0 unpreserved device RDIFFN_device_RES_58
4164 0 unstable device for RDIFFP_device_RES_57
4165 0 unpreserved device RDIFFP_device_RES_57
4166 0 unstable device for RNWELL_device_RES_56
4167 0 unpreserved device RNWELL_device_RES_56
4168 0 unstable device for ESDGCP5_device_Device_55
4169 0 unpreserved device ESDGCP5_device_Device_55
4170 0 unstable device for ESDFDP5_device_Device_54
4171 0 unpreserved device ESDFDP5_device_Device_54
4172 0 unstable device for ESDGCN5_device_Device_53
4173 0 unpreserved device ESDGCN5_device_Device_53
4174 0 unstable device for ESDFDN5_device_Device_52
4175 0 unpreserved device ESDFDN5_device_Device_52
4176 0 unstable device for ESDPD30_device_Device_51
4177 0 unpreserved device ESDPD30_device_Device_51
4178 0 unstable device for ESDPD26_device_Device_50
4179 0 unpreserved device ESDPD26_device_Device_50
4180 0 unstable device for ESDPD18_device_Device_49
4181 0 unpreserved device ESDPD18_device_Device_49
4182 0 unstable device for ESDPD12_device_Device_48
4183 0 unpreserved device ESDPD12_device_Device_48
4184 0 unstable device for SBD5_device_sbdcon_Device_47
4185 0 unpreserved device SBD5_device_sbdcon_Device_47
4186 0 unstable device for PHDNWB850_device_pad_barc_Device_46
4187 0 unpreserved device PHDNWB850_device_pad_barc_Device_46
4188 0 unstable device for PHDNWA850_device_ntub_Device_45
4189 0 unpreserved device PHDNWA850_device_ntub_Device_45
4190 0 unstable device for ZD2SM24_device_DIODE_44
4191 0 unpreserved device ZD2SM24_device_DIODE_44
4192 0 unstable device for P_NWD_device_Device_43
4193 0 unpreserved device P_NWD_device_Device_43
4194 0 unstable device for NWD_device_DIODE_42
4195 0 unpreserved device NWD_device_DIODE_42
4196 0 unstable device for P_PD_device_Device_41
4197 0 unpreserved device P_PD_device_Device_41
4198 0 unstable device for PD_device_DIODE_40
4199 0 unpreserved device PD_device_DIODE_40
4200 0 unstable device for P_ND_device_Device_39
4201 0 unpreserved device P_ND_device_Device_39
4202 0 unstable device for ND_device_DIODE_38
4203 0 unpreserved device ND_device_DIODE_38
4204 0 unstable device for PMOS30M_device_Device_37
4205 0 unpreserved device PMOS30M_device_Device_37
4206 0 unstable device for PMOSD30M_device_Device_36
4207 0 unpreserved device PMOSD30M_device_Device_36
4208 0 unstable device for NMOS18T_device_Device_35
4209 0 unpreserved device NMOS18T_device_Device_35
4210 0 unstable device for NMOS30M_device_Device_34
4211 0 unpreserved device NMOS30M_device_Device_34
4212 0 unstable device for NMOSMHL_device_Device_33
4213 0 unpreserved device NMOSMHL_device_Device_33
4214 0 unstable device for NMOSHL_device_Device_32
4215 0 unpreserved device NMOSHL_device_Device_32
4216 0 unstable device for NMOSMH_device_Device_31
4217 0 unpreserved device NMOSMH_device_Device_31
4218 0 unstable device for NMOSH_device_Device_30
4219 0 unpreserved device NMOSH_device_Device_30
4220 0 unstable device for PMOSMW_2N_device_Device_29
4221 0 unpreserved device PMOSMW_2N_device_Device_29
4222 0 unstable device for PMOSMW_3N_device_Device_28
4223 0 unpreserved device PMOSMW_3N_device_Device_28
4224 0 unstable device for PMOSMW_4N_device_Device_27
4225 0 unpreserved device PMOSMW_4N_device_Device_27
4226 0 unstable device for PMOSW_2N_device_Device_26
4227 0 unpreserved device PMOSW_2N_device_Device_26
4228 0 unstable device for PMOSW_3N_device_Device_25
4229 0 unpreserved device PMOSW_3N_device_Device_25
4230 0 unstable device for PMOSW_4N_device_Device_24
4231 0 unpreserved device PMOSW_4N_device_Device_24
4232 0 unstable device for NMOSMW_2N_device_Device_23
4233 0 unpreserved device NMOSMW_2N_device_Device_23
4234 0 unstable device for NMOSMW_3N_device_Device_22
4235 0 unpreserved device NMOSMW_3N_device_Device_22
4236 0 unstable device for NMOSMW_4N_device_Device_21
4237 0 unpreserved device NMOSMW_4N_device_Device_21
4238 0 unstable device for NMOSW_2N_device_Device_20
4239 0 unpreserved device NMOSW_2N_device_Device_20
4240 0 unstable device for NMOSW_3N_device_Device_19
4241 0 unpreserved device NMOSW_3N_device_Device_19
4242 0 unstable device for NMOSW_4N_device_Device_18
4243 0 unpreserved device NMOSW_4N_device_Device_18
4244 0 unstable device for PMOSML_WAFFLE_device_Device_17
4245 0 unpreserved device PMOSML_WAFFLE_device_Device_17
4246 0 unstable device for DPMOSM_device_Device_16
4247 0 unpreserved device DPMOSM_device_Device_16
4248 0 unstable device for PMOSML_device_Device_15
4249 0 unpreserved device PMOSML_device_Device_15
4250 0 unstable device for PMOSL_WAFFLE_device_Device_14
4251 0 unpreserved device PMOSL_WAFFLE_device_Device_14
4252 0 unstable device for PMOSL_device_Device_13
4253 0 unpreserved device PMOSL_device_Device_13
4254 0 unstable device for NMOSML_WAFFLE_device_Device_12
4255 0 unpreserved device NMOSML_WAFFLE_device_Device_12
4256 0 unstable device for NMOSML_device_Device_11
4257 0 unpreserved device NMOSML_device_Device_11
4258 0 unstable device for NMOSL_WAFFLE_device_Device_10
4259 0 unpreserved device NMOSL_WAFFLE_device_Device_10
4260 0 unstable device for NMOSL_device_Device_9
4261 0 unpreserved device NMOSL_device_Device_9
4262 0 unstable device for PMOSM_WAFFLE_device_Device_8
4263 0 unpreserved device PMOSM_WAFFLE_device_Device_8
4264 0 unstable device for PMOSM_device_MOS_7
4265 0 unpreserved device PMOSM_device_MOS_7
4266 0 unstable device for PMOS_WAFFLE_device_Device_6
4267 0 unpreserved device PMOS_WAFFLE_device_Device_6
4268 0 unstable device for PMOS_device_MOS_5
4269 0 unpreserved device PMOS_device_MOS_5
4270 0 unstable device for NMOSM_WAFFLE_device_Device_4
4271 0 unpreserved device NMOSM_WAFFLE_device_Device_4
4272 0 unstable device for NMOSM_device_MOS_3
4273 0 unpreserved device NMOSM_device_MOS_3
4274 0 unstable device for NMOS_WAFFLE_device_Device_2
4275 0 unpreserved device NMOS_WAFFLE_device_Device_2
4276 0 unstable device for NMOS_device_MOS_1
4277 0 unpreserved device NMOS_device_MOS_1
